### ISSUE TITLE
Notification reminder not being sent out

### ISSUE THREAD

**Issue by fahadhaq** [DNNCommunity/DNN.Events#10]
Hi,

I am using version 06.01.04 and I have looked at all the tables and code but not sure why the notification not being sent. I can see that the reminder is set on the event. The users are there correctly as well. Not sure if this is something you guys can help with.

Thanks in advance

**Comment by EPTamminga** [comment]
Is the schedule running to send notifications?
Is the SMTP for the site working correctly?
Which version of DNN?

**Comment by fahadhaq** [comment]
the schedule is running and is set to a 5 min interval. The SMTP server is working as I get sent email when I register to the site. Version of DNN is 07.03.02

**Comment by EPTamminga** [comment]
Can you give me (host) access to your site, so I can have a look? You can skype chat (ernst.peter.tamminga) me any login/url info if you want me to do that.

**Comment by EPTamminga** [comment]
No further info obtained. Closing issue
