### ISSUE TITLE
Scheduled task generates unhandled exceptions in the site log

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/DNN.Events#107]
## Describe the bug
Scheduled task generates unhandled exceptions in the site log

## To Reproduce
We just need to run the scheduler in debug mode and step through the code to see the unhandled exceptions. I think it relates to changes to time utilities in the Dnn APIs.

**Comment by valadas** [comment]
That was on Dnn 9.1.1 instance.

**Comment by EPTamminga** [comment]
I cannot reproduce this in my current Events 7.0.3 (under development). 
Since I corrected a whole lot of string comparisons, it might be solved by that. 
Closing issue now. If the error resurfaces, reopen the issue
