### ISSUE TITLE
Sub-calendar names missing

### ISSUE THREAD

**Issue by PeterCasper** [DNNCommunity/DNN.Events#108]
## Describe the bug
v7.0.2 Dub-calendars detected but names not conveyed to parent calendar.

## To Reproduce
1. Go to 'Edit Settings'
2. Click on 'Sub-calendar tab'
3. Turn on 'Include Other Site Event Modules'
4. See 'Available' contains (in my case 21) blank lines.
5. Click on blank lines in 'Available'.
6. Click on '>>'.
7. "See" blank lines under 'Selected' (Several so slide bar now present.)
7. Click on 'Update Settings'.
8. See main calendar now populated with sub-calendar events with empty brackets not holding sub-calendar names.
9. Click elsewhere then return to main calendar.
10 Notice all sub-calendar events are now gone.
11. Go to 'Edit Settings'
12. Click on 'Sub-calendar tab'
13. See previously set Sub-calendar settings are removed.

## Expected behavior
* See names under ' Available' & 'Selected'
* See on calendar 'event name (Sub name)'
* settings to not revert.

## Error log
Attached
[errorlog.zip](https://github.com/DNNCommunity/DNN.Events/files/2191179/errorlog.zip)

**Comment by jasclar** [comment]
same issue

**Comment by EPTamminga** [comment]
Solved
