### ISSUE TITLE
Error definition for 'SelectCategory_CategorySelected'

### ISSUE THREAD

**Issue by worldheadquarters** [DNNCommunity/DNN.Events#109]
I deleted the only event that had been added (a daily recurring event for 29 days) which rendered the calendar  correctly with no events.  I changed the default display to "list", checked "allow owner change" and set to delete events older than 30 days and saved the change.  Now  when rendering the module, the following error displays:  I added a new instance of Events on another page, but have been unable to reproduce the error (have not added an events to that instance(.  This is version 7.0.0.2 with DNN 9.2

Error: Events is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: d:\webhost\dnndev.me\Website\DesktopModules\Events\EventRpt.ascx(11): error CS1061: 'ASP.desktopmodules_events_eventrpt_ascx' does not contain a definition for 'SelectCategory_CategorySelected' and no extension method 'SelectCategory_CategorySelected' accepting a first argument of type 'ASP.desktopmodules_events_eventrpt_ascx' could be found (are you missing a using directive or an assembly reference?) ---> System.Web.HttpCompileException: d:\webhost\dnndev.me\Website\DesktopModules\Events\EventRpt.ascx(11): error CS1061: 'ASP.desktopmodules_events_eventrpt_ascx' does not contain a definition for 'SelectCategory_CategorySelected' and no extension method 'SelectCategory_CategorySelected' accepting a first argument of type 'ASP.desktopmodules_events_eventrpt_ascx' could be found (are you missing a using directive or an assembly reference?) at System.Web.Compilation.BuildManager.PostProcessFoundBuildResult(BuildResult result, Boolean keyFromVPP, VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetBuildResultFromCacheInternal(String cacheKey, Boolean keyFromVPP, VirtualPath virtualPath, Int64 hashCode, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultFromCacheInternal(VirtualPath virtualPath, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath) at DotNetNuke.Modules.Events.Events.LoadModuleControl() --- End of inner exception stack trace ---
Copyright 2018 by DNN Corp Terms Of Use | Privacy Statement

**Comment by curioustoknow2019** [comment]
Hello, 

I just recently upgraded the module from v 6.3.1 to 7.0.2 and then upgraded from dnn 9.1.1 to 9.3.0 and now I receiving similar error:

`Error: Events is currently unavailable.DotNetNuke.Services.Exceptions.ModuleLoadException: c:\inetpub\wwwroot\Dnn\DesktopModules\Events\EventRpt.ascx(11): error CS1061: 'ASP.desktopmodules_events_eventrpt_ascx' does not contain a definition for 'SelectCategory_CategorySelected' and no extension method 'SelectCategory_CategorySelected' accepting a first argument of type 'ASP.desktopmodules_events_eventrpt_ascx' could be found (are you missing a using directive or an assembly reference?) ---> System.Web.HttpCompileException: c:\inetpub\wwwroot\Dnn\DesktopModules\Events\EventRpt.ascx(11): error CS1061`
