### ISSUE TITLE
Question about layout in list view

### ISSUE THREAD

**Issue by supermansrf** [DNNCommunity/DNN.Events#11]
Sorry this isn't as much of an issue as a question.  I have several modules set to default to list view.  I have 3 columns showing; Event start, title and category.  I would like to move the category to be between the event start and category.  Is there an easy way to do this?

**Comment by EPTamminga** [comment]
Have you tried the repeater view? That is an enhanced version of the list view and completely templatable.

**Comment by supermansrf** [comment]
Thanks @EPTamminga - I'll try to figure this out and see if I can get it working.  I remember trying to use the repeater view a while back and confused myself.  I'm sure if I try hard enough I can figure it out :sweat_smile:

**Comment by EPTamminga** [comment]
No further news. Closing issue.
