### ISSUE TITLE
No available information on compatibility of current version of Events and current version of DNN

### ISSUE THREAD

**Issue by abukres** [DNNCommunity/DNN.Events#118]
I am getting a server error when I click 'Moderate Event'. Before I spend time reporting an error or a bug, I can't find any information on whether the current version of Events, 7.0.2, is compatible with the current version of DNN, 9.2. 

The Wiki page seems to show the minimum requirements but that doesn't tell me if the current Events module is compatible with the current DNN version. It's helpful if the wiki is always updated to the latest versions of the module and DNN.

**Comment by EPTamminga** [comment]
DNN.Events 7.x is compliang with DNNPlatform up to 9.2.
So if yiu find issues, document them here.
