### ISSUE TITLE
Sub-calendar settings not saved

### ISSUE THREAD

**Issue by PeterCasper** [DNNCommunity/DNN.Events#119]
## Describe the bug
I can now set sub-calendars using a patch from Mark-89 however the settings are not being retained.

## To Reproduce

Edit Settings
Sub-calendar tab
"Include Other Site Event Modules" set check-mark on.
>> (Moves 20+ sub-calendars to "Selected")
Update Setings
(Calendar & sub-calendars display correctly).
Close browser, reopen & log in
(root calendar displayed with no sub-calendars)
Edit Settings
Sub-calendar tab
"Include Other Site Event Modules" has reverted to unchecked.
"Include Other Site Event Modules" set check-mark on.
sub-calendars are no longer selected.

## Expected behavior
"Include Other Site Event Modules"check-mark to remain on.
sub-calendars to remain selected.

**Comment by EPTamminga** [comment]
Could not reproduce (solved) in V07.00.03
