### ISSUE TITLE
Can't create new event when edit time interval set to 1440

### ISSUE THREAD

**Issue by supermansrf** [DNNCommunity/DNN.Events#12]
Just as the titles says.  We have multiple calendars on multiple pages.  The last change I made was to change the edit time interval to 1440.  After that, creating a new event freezes up.  The editor doesn't load, the page falls on its face and refuses to load.  

Back out, change the setting back to 60 minutes and everything is fine again.

**Comment by EPTamminga** [comment]
I mark this as an error. 
Time interval tries to divide a day into timeslots. If the timeslot is specified as a day (1440 min), I think there is an edge case where it loops.

**Comment by hallmatt** [comment]
This seems to still be an issue.
