### ISSUE TITLE
Tooltip Popup is in the way of clicking on event links in List View

### ISSUE THREAD

**Issue by thabaum** [DNNCommunity/DNN.Events#123]
## Describe the bug
After posting an event and you hover your mouse over a list view item you cannot click on the event to go to the full description

## To Reproduce
1. Create a calendar in List View
2. Hover over the event
3. Popup gets in the way of clicking on the event to see full details page

## Expected behavior
Hover over event and see a popup with a link that gets you to the full description

## Additional context
When posting an event with "Custom Page" the event in list view reveals a magnify glass.  When you hover this you see the event description/summary.  Click on the event link and it goes to the custom page however you have to be fast enough to beat the popup or you cannot select it.

Instead of having the entire column popup, only have the popup when the magnify glass is hovered.

If you click on the magnify glass right now you go to the site event page instead of custom page url.

- [ ] Review standard templates to get better initial display

**Comment by EPTamminga** [comment]
@thabaum: Can you provide a screenshot or elaborate what is wrong?

This is what I get in list view:

![image](https://user-images.githubusercontent.com/5859855/43588208-466251fa-966c-11e8-8b22-f38654cf2aaf.png)

**Comment by thabaum** [comment]
Kind of funny I can put one up but not with generic content so I wont.

What happening is my older events (reuccuring) are using the old template I suppose, but if I put a new event in it works as you have pictured.

Good enough for me for now I suppose but my recurring events have that issue still I believe.

![dnn-events-categories-overlapping](https://user-images.githubusercontent.com/13577556/44302907-8bb77000-a2e7-11e8-9b62-13ce875f75d3.png)
![dnn-events-notes](https://user-images.githubusercontent.com/13577556/44302909-91ad5100-a2e7-11e8-9286-b64c2d68f6ff.png)

here are a couple other things I noticed... didnt realize I could just drop screenshots here into github this will help I was looking for how to do this but now see the note below (when I was looking on top for a way)

**Comment by thabaum** [comment]
Also test NOTES is waht gets displayed it is very confusing.

Notes are notes, a summary is a summary so where do you put a full description?

Need to take out some guess work make this easier to work with for a user.   It has always annoyed me.  I may have better luck trying to work on this module with you for a while instead of trying to figure out the DNN Register using Email as Username issue I have been beating myself up on :)

**Comment by thabaum** [comment]
OK now after adding/editing a new event the recurring events popup now shows under the link.

I guess I just needed to add a new event to make the changes take.
