### ISSUE TITLE
Feature request - sub-calendar showing only selected categories

### ISSUE THREAD

**Issue by supermansrf** [DNNCommunity/DNN.Events#13]
So I'm just curious to hear other user's thoughts on this.  I was asked the question so I want to pass along my thoughts and possibly help out if others agree.  

I religiously use the master/sub calendar feature.  We have a multi-tenant setup on one very large website. The site is about the international main company, the company is divided up into regions, and within the regions there are local locations.  

We have things setup where placing an event on the local location writes up to the region it belongs to.  Then those write up to the main calendar.  The local locations like to include everything on their calendars, a lot of them are recurring events.  All of these recurring events will be grouped into a specific category.  

What I would like to be able to do is to restrict what "writes up" based on the category.  This way we don't have 300 locations all putting recurring (not important) events on the main master calendar.  But other events that they will put on their calendar need to be shown on the master calendar.  

I'm curious to hear if anyone else would be able to benefit from this, or how the feature would work.  I'm just thinking about under the sub-calendar area, have the categories there with check boxes.  Then you could check off what categories you want to include.  

I know how things usually work around here so I'm not asking anyone to do the work for me (unless you are just interested in it).  I'm curious to hear if I would pursue this if it would be allowed and included if I had this built into the module.  What I don't want is to have our own flavor of DNN Events module that we will constantly have to create a custom build for each time you come out with new features and updates.  

Thanks in advance

**Comment by EPTamminga** [comment]
Thank you for your well written and argumented feature request. I am curious is this is a scenario that more users come across. It looks like that a change like this could be implemented without functional impact on users who do not need it, which is good.
As for changes, I am very much interested in pull requests that provide fixes and general enhancements.

**Comment by djamell** [comment]
While I have not encountered a situation to require this, I can see how it would be more efficient and an improvement.
