### ISSUE TITLE
ArgumentOutOfRange on iCal export

### ISSUE THREAD

**Issue by EPTamminga** [DNNCommunity/DNN.Events#130]
## Describe the bug
Error when trying to export iCal

## To Reproduce
Steps to reproduce the behaviour:
Create an event, display details, click export

## Expected behaviour
iCal file generated and downloaded

**Comment by chitraworld** [comment]
I get an error when click export in the event description level and iCal icon.

**Comment by EPTamminga** [comment]
@chitraworld That is what this issue is about. WIll be solved in the next release
