### ISSUE TITLE
RSS Feed / Event Sitemap not working for latest version 7.0.2

### ISSUE THREAD

**Issue by brewadmin** [DNNCommunity/DNN.Events#134]
## Describe the bug
Upgraded DNN.Events from version 6.3.1 and the RSS feed stopped working. The SEO sitemap stopped showing the events.

**Comment by EPTamminga** [comment]
OK, it took quite some time debugging, but I found the problem with RSS feed not displaying: a result of a difference between VB.net (original source) and C# in string handling in empty strings. 
I assume the SEO sitemap has similar issues, keep posted.

**Comment by brewadmin** [comment]
Cool, looking forward to 7.3

 

Kind regards

 

Brent Wilson

ITM Website Design, SEO and Digital Marketing

084 7515 616

 <http://www.itm.co.za> www.itm.co.za

**Comment by EPTamminga** [comment]
@brewadmin Sitemap issue also covered.
If I create a test version, are you able to try it out on a test environment to check if the RSSFeed and SiteMap bug are fixed?

**Comment by brewadmin** [comment]
Sure no problem

 

Send the install to me

 

My test site on dnn8 is test.itm.co.za

 

Kind regards

 

Brent Wilson

ITM Website Design, SEO and Digital Marketing

084 7515 616

 <http://www.itm.co.za> www.itm.co.za

**Comment by EPTamminga** [comment]
@brewadmin Testversion as ALFA install zip in this comment.
[DNN_Events_07.00.03_Install (ALFA).zip](https://github.com/DNNCommunity/DNN.Events/files/2405594/DNN_Events_07.00.03_Install.ALFA.zip)

**Comment by brewadmin** [comment]
RSS working

 

http://test.itm.co.za/DesktopModules/Events/EventRSS.aspx?mid=7299 <http://test.itm.co.za/DesktopModules/Events/EventRSS.aspx?mid=7299&tabid=3230> &tabid=3230

 

Sitemap

 

Not working – 

 

http://test.itm.co.za/sitemap.aspx 

 

Kind regards

 

Brent Wilson

ITM Website Design, SEO and Digital Marketing

084 7515 616

 <http://www.itm.co.za> www.itm.co.za

**Comment by EPTamminga** [comment]
Sitemap is cached by DNN for at least a day. Try to delete the sitemap.??-??.xml in the cache folder of your portal.

**Comment by brewadmin** [comment]
I disabled cache when I installed the module and flushed it.

 

The Enable Search Engine Sitemap checkbox setting is not binding

 

Kind regards

 

Brent Wilson

ITM Website Design, SEO and Digital Marketing

084 7515 616

 <http://www.itm.co.za> www.itm.co.za

**Comment by EPTamminga** [comment]
Which version of DNN are you using?

**Comment by EPTamminga** [comment]
I leave it open until I am sure sitemap is fixed

**Comment by brewadmin** [comment]
On the test site I am using 8.0.4

**Comment by EPTamminga** [comment]
OK, tried it and I can reproduce. 

The old (Events 6.0.3) sitemap setting ON is not carried forward to 7.0.3. If I upgrade, checkbox is not checked., where it was in 6.0.3. If I check it/save the sitemap setting in 7.0.3, the sitemap is created correctly.

I will create a new issue for this (and solve it for 7.0.3).

@brewadmin Tnx for the feedback.
