### ISSUE TITLE
Template Changes not binding in 7.0.2

### ISSUE THREAD

**Issue by brewadmin** [DNNCommunity/DNN.Events#137]
## Describe the bug
I was unable to update a template change, the change not binding on update

## Error log
**Note: Debug DLL's**
Please replace the current extension DLL's with the debug DLL's (if these are available with the release) and reproduce the error with the debug DLL's before pasting the error log.

Paste the error log that is related to this issue.

**Comment by EPTamminga** [comment]
This is a known bug (Issue #128 ) and is fixed in the next (7.0.3) release.
