### ISSUE TITLE
Journal Security

### ISSUE THREAD

**Issue by teambound** [DNNCommunity/DNN.Events#141]
In group mode, when an event is added to the journal, the journal security is set to userid so the journal entry cannot be seen by anyone.  If someone is visiting the group, they should be able to see the journal entries for the events.  In the RSS/ICAL/SOCIAL the following settings are there for public/edit by group/private but these setting seem to pertain to the event itself.  

When set to Public users with view/edit permissions can see/edit all events. When set to Edit By Group, events are visible to all but only editable by group members who have edit permissions. When set to private, events are only visible by group members. 

Can this also be tied to the journal entry? I want the events and **journal** to be visible to public in addition to just the group.

Thanks

**Comment by EPTamminga** [comment]
I have to investigate how this can be done. I have not bothered about journal entries before.

**Comment by thabaum** [comment]
I am looking at working with journal items and wish to understand how to work with them better.  Can you better explain what feature you are looking to have created here.  Not saying I can do anything but I might be able to help the discussion.

` I want the events and journal to be visible to public in addition to just the group.`
