### ISSUE TITLE
Templates do not update

### ISSUE THREAD

**Issue by teambound** [DNNCommunity/DNN.Events#142]
## Describe the bug
Cannot Update Templates. Tried to modify the event detail template but updates are not saved.

## To Reproduce
1. Go to templates
2. make change
3. save changes
4. see no effect

## Expected behavior
updated template

## Error log
**Note: Debug DLL's**
Please replace the current extension DLL's with the debug DLL's (if these are available with the release) and reproduce the error with the debug DLL's before pasting the error log.

Paste the error log that is related to this issue.

**Comment by EPTamminga** [comment]
This is solved in the upcoming release 7.0.3
See also issue #137 and PR #135
