### ISSUE TITLE
EventGetByRange Query Running constantly 

### ISSUE THREAD

**Issue by HarrisCounty** [DNNCommunity/DNN.Events#144]
We are using events module in our DNN 9.1.1 platform. 
End of last month we have noticed that the EventGetbyRange query is running constantly on our DB server and using almost 100% of the cpu. Can you please help us figure this issue. Our database team have suggested to index that EventGetByRange query. would this help? 
![eventgetbyrange-query](https://user-images.githubusercontent.com/33842540/46560312-d2255600-c8b8-11e8-95b7-0de90f890648.png)

**Comment by EPTamminga** [comment]
Can you explain a bit more about the Events content? How many events? Users? Locations? Categories? Date range? Recurring or not?

I did not receive any similar problem before
