### ISSUE TITLE
iCAL Does Not Display Sub-Calendar Name in Subject

### ISSUE THREAD

**Issue by PeterCasper** [DNNCommunity/DNN.Events#150]
## Describe the bug
I have 20+ sub-calendars with event subjects of "Rehearsal", "Regular Meeting", etc. On the parent calendar they are displayed as "Event Name(Sub-Calendar Name)". The iCAL output shows subjects of "Event Name".

## To Reproduce
1. Go to a sub-calendar & create an event.
2. Go to parent calendar & see event with dub-calendar name.
3. Generate an iCAL output.
4. Open iCAL output in Outlook or similar.

## Expected behavior
iCAL Subject: "Event Name(Sub-Calendar Name)"

## Screenshots
![image](https://user-images.githubusercontent.com/25318978/46900198-cf8eb600-cee1-11e8-9b5b-b824f7febf79.png)
![image](https://user-images.githubusercontent.com/25318978/46900208-f1883880-cee1-11e8-880a-beb9d25d0952.png)

## Error log
None
## Additional context
Is this something I can manage in templates?

Peter

**Comment by PeterCasper** [comment]
Ernst, I am still receiving requests from users for the Sub-Calendar names. Without them, the event descriptions are incomplete. Can you squeeze it into the update?

Peter 
![Capture](https://user-images.githubusercontent.com/25318978/54134494-ce978b80-4463-11e9-94e0-cfb501d481f1.PNG)

**Comment by EPTamminga** [comment]
I understand your request. I will do my best :-)

**Comment by EPTamminga** [comment]
Still relevant

**Comment by PeterCasper** [comment]
Bump?

**Comment by PeterCasper** [comment]
I'm still receiving requests for this.

**Comment by PeterCasper** [comment]
Bump
