### ISSUE TITLE
Setttings show a blank screen on DNN v. 09.02.00 (366)

### ISSUE THREAD

**Issue by qquestel** [DNNCommunity/DNN.Events#153]
## Describe the bug
Clicking on settings or add new event shows a blank screen.

![capture](https://user-images.githubusercontent.com/6721893/47146003-1fca9700-d299-11e8-87df-2931267ea592.PNG)

**Comment by EPTamminga** [comment]
I cannot reproduce this in my latest DNN 07.00.03 version, so I assume it is resolved
