### ISSUE TITLE
All Actions lead to Blank Modal DNN 09.02.02

### ISSUE THREAD

**Issue by kenny-sellers** [DNNCommunity/DNN.Events#154]
Working on a new site for a client and all actions lead to empty modals. This is a clean install of DNN. Edit Settings, Edit Categories, Edit Locations, and Add Event lead to the following screenshot.

![image](https://user-images.githubusercontent.com/23708301/47757873-698e8680-dc76-11e8-99fe-4b879c8dab08.png)

**Comment by valadas** [comment]
Can you please add some details to the issue... What version of the module, what version of Dnn, does it happen with the standard skin, do you have any logged errors in:
- The browser console (F12 in most broswers)
- The Dnn Admin log
- In the Portals/_default/logs log files

**Comment by valadas** [comment]
Oop, forget about dnn version, just read the title...

**Comment by kenny-sellers** [comment]
Dan, This is with version 07.00.03 of the events module, 9.2.2 of DNN. The site is using the Porto Skin. I can try finding a base install of dnn to test on the standard skin.

**Comment by nvisionative** [comment]
Related issue #153

**Comment by valadas** [comment]
@kenny-sellers I wont have time to test this very soon, but did you get a chance at looking for error logs?

**Comment by mauricioonia** [comment]
It does not generate errors in the log file, in my case I use the version 07.00.03 of the events module, 9.1.1 of DNN, the error remains.

**Comment by FrancSimari** [comment]
I had the same issue with dnn 9.1.1 on a virgin event install. 
I uninstalled events 7.0.3 installed events 7.0.2 popup looks good no blank. update to 7.0.3 popup still looks good and fully operational. Not great for  mobile  devices..

**Comment by thenotandy** [comment]
I have the same issue. 7.0.2 works, but 7.0.3 does not.

**Comment by EPTamminga** [comment]
Solved in the latest V07.00.03 pre-release version
