### ISSUE TITLE
Error installing 7.0.3 on dnn 8.0.4

### ISSUE THREAD

**Issue by FrancSimari** [DNNCommunity/DNN.Events#155]
## Describe the bug
This is the error I receive when trying to install on DNN 8.0.4. I also tried again after uninstalling events 7.0.2

Info | Processing Cleanup File - 7.0.3
-- | --
Failure | ExceptionSchwabenCode.QuickIO.UnmatchedFileSystemEntryTypeException: FileSystemEntryType not matched! at SchwabenCode.QuickIO.QuickIOFile.InternalFileExists(String uncPath) at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFiles(Array arrPaths) at DotNetNuke.Services.Installer.Installers.CleanupInstaller.ProcessCleanupFile()
Failure | Installation Failed - Cleanup
Info | Rolling back component install - Script
Info | Restored backup of previous version - Installation\Uninstall.SqlDataProvider
Info | Component rolled back successfully - Script
Info | Rolling back component install - Module
Info | Component rolled back successfully - Module
Info | Rolling back component install - Assembly
Info | Restored backup of previous version - bin\DotNetNuke.Modules.Events.dll
Info | Restored backup of previous version - bin\DotNetNuke.Modules.Events.ScheduleControl.dll
Info | Component rolled back successfully - Assembly
Info | Rolling back component install - ResourceFile
Failure | Exception - Could not find file 'C:\inetpub\tomzey\Newtomzey\Install\Temp\kvwlrlvfresources.zip'.
Info | Component rolled back successfully - ResourceFile
Info | Installation Failed - DNN_Events
Info | Deleted temporary install folder
EndJob | Installation Failed

the attached file is the event logged when I tried to re install "events" after clearing cache and restarting the application I hope some of this helps. 
Thank you for any help. 

[logged event.txt](https://github.com/DNNCommunity/DNN.Events/files/2617543/logged.event.txt)

**Comment by EPTamminga** [comment]
I could not reproduce this error. I created a clean DNN804, installed DNNEvents703, added the module to a page, uninstalled (with Delete files) DNNEvents703 without a problem.

**Comment by FrancSimari** [comment]
this error occurred when updating from 7.0.2 to 7.0.3 
also failed after uninstalling 7.0.2 and trying to install a new instance of 7.0.3 on the same DNN 8.0.4 instance. 
I believe 7.0.3  has installed fine on clean new DNN instances.

**Comment by EPTamminga** [comment]
Ok, I will try to reproduce.

**Comment by FrancSimari** [comment]
I think it had to do with the database cleanup not sure do.

**Comment by EPTamminga** [comment]
OK, I reproduced the install error. The installer has a problem with the cleanup file in Events 703, where I try to clean (remove) a folder that is not needed anymore in the Desktopmodules/Events (tmpCompressCSS). This folder contains subfolders and the DNN installer on DNN804 generates an error. 
I have not come across this behaviour earlier. 
I will change the cleanup instructions, so that all the subfolders will be removed first, before removing the main folder.
