### ISSUE TITLE
Blank Modals with fresh event install

### ISSUE THREAD

**Issue by FrancSimari** [DNNCommunity/DNN.Events#156]
## Describe the bug
Installed fine on dnn 9.1.1
installed events on page. Looks good. 
Clicked the setting button. blank modal popup opens cannot make changes. 

I uninstalled 7.0.3 installed 7.0.2 and I was able to access settings.

I upgraded 7.0.2 to 7.0.3 the upgrade threw the error below. Events 7.0.3 did install and settings are accessible. will try to changing and testing and will update. 

"Info::Starting Installation - Cleanup

Info::Processing Cleanup File - 7.0.3

Info::ExceptionSchwabenCode.QuickIO.UnmatchedFileSystemEntryTypeException: FileSystemEntryType not matched! at SchwabenCode.QuickIO.QuickIOFile.InternalFileExists(String uncPath) at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFiles(Array arrPaths) at DotNetNuke.Services.Installer.Installers.CleanupInstaller.ProcessCleanupFile()

Info::Completed Processing of Cleanup File - 7.0.3

## To Reproduce
I need to give you access to website, no problem with that. 

## Error log
**Note: Debug DLL's**
Please replace the current extension DLL's with the debug DLL's (if these are available with the release) and reproduce the error with the debug DLL's before pasting the error log.

Paste the error log that is related to this issue.

**Comment by MaiklT** [comment]
I can reproduce this behaviour. It seems that there are missing control definitions in the manifest.

**Comment by EPTamminga** [comment]
I did not find time to investigate. If you can produce a PR, you are most welcome.

**Comment by MaiklT** [comment]
Ernst, I uploaded an updated manifest in the post above. There are just some control definitions missing. I'll make a PR when I find time...
