### ISSUE TITLE
Cannot Add an Event

### ISSUE THREAD

**Issue by IrishChieftain** [DNNCommunity/DNN.Events#159]
## Please summarize your question in one sentence
This was just installed in DNN 9.2. When I try to add an event, the modal comes up blank. Clicking the edit settings icon also yields a blank modal.

## Give a more extended description
We have an older version of this module installed on an older version of DNN (8.4). So I tried to copy the same settings in the new module. When I went to edit the extension settings in 9.2, I had another issue when trying to edit the Events module definitions. Specifically, the source file drop down list entries are all truncated, making them unreadable. So you have no idea what you're adding.

**Comment by FrancSimari** [comment]
I had the same issue. You may want to try what I did,
I deleted  Events V7.0.3 and installed Events V7.0.2.
You can check and see that everything works fine. 
I then upgraded to events V7.0.3 and it worked fine also. 
Merry Christmas

**Comment by IrishChieftain** [comment]
Looks like the reason the modal was coming up empty was because I had to add all the controls first. Duh. But I still faced the problem of not being able to read the value in the source file drop down list. So I used my browser tools to inspect the drop down, took a screen shot of the values and then counted to the correct value. Hacky but it worked :)
