### ISSUE TITLE
Next / Previous Month Control Not Working

### ISSUE THREAD

**Issue by ghost** [DNNCommunity/DNN.Events#16]
I am running DNN Host v. 7.3.3 and Events 6.1.1 

Situation #1: Viewer of website is not logged in module has BUG. 

When viewing the calendar and trying to proceed to the upcoming or previous month by clicking on the Month Name control the 1st Upcoming month will display; however, when trying to proceed to the next upcoming month, the page just hangs and does not reload. see video: http://screencast.com/t/rU5yduTlYRyq 

Situation #2: Viewer is a DNN user who is logged in. 

Module works fine. See video. http://screencast.com/t/YMGQClOoKF 

I have confirmed this same problem when using many different skins including the default Gravity Skin. 

Thank you very much for any help or support.

**Comment by EPTamminga** [comment]
I verified & tried to repeat the problem but I could NOT reproduce it.

Plain vanilla DNN 7.3.3 (blank website) out of the box, Events 6.2.1; Events installed on the single page, NO PROBLEM in clicking on the months forward and backward

Repeated the same procedure with DNN 7.4.4, again, no problem.

Repeated the cycle with both Events Install version as well as Source version. Again, no problem.

Repeated for DNN733 with (HOST) Client Resource Management ON, minify/combine CSS and JS. Again ,no problem.

Test environment:
Windows 8.1, SQL2014, IIS8.5

**Comment by davegambino** [comment]
Were you able to test this WITHOUT being logged in as a DNN User?



The problem does not happen when logged in. …. Only public visitors to the
website.



Here is an example of one of many of my sites that is having the problem:
http://saintbridgetchurch.org/Resources/Calendar.aspx



Can you think of what may be conflicting with my builds?



Thanks so much for your time.



*Dave Gambino*

dave@smbcreativegroup.com

1-800-980-0906 x 705



*SMB Creative Group*



*Our Services*

www.CatholicChurchWebsites.com |  www.SMBCreativeGroup.com
<http://www.smbcreativegroup.com/>



*From:* Ernst Peter Tamminga [mailto:notifications@github.com]
*Sent:* Wednesday, November 04, 2015 8:41 AM
*To:* DNNCommunity/DNN.Events <DNN.Events@noreply.github.com>
*Cc:* davegambino <dave@smbcreativegroup.com>
*Subject:* Re: [DNN.Events] Next / Previous Month Control Not Working (#16)



I verified & tried to repeat the problem but I could NOT reproduce it.

Plain vanilla DNN 7.3.3 (blank website) out of the box, Events 6.2.1;
Events installed on the single page, NO PROBLEM in clicking on the months
forward and backward

Repeated the same procedure with DNN 7.4.4, again, no problem.

Repeated the cycle with both Events Install version as well as Source
version. Again, no problem.

Repeated for DNN733 with (HOST) Client Resource Management ON,
minify/combine CSS and JS. Again ,no problem.

Test environment:
Windows 8.1, SQL2014, IIS8.5

—
Reply to this email directly or view it on GitHub
<https://github.com/DNNCommunity/DNN.Events/issues/16#issuecomment-153747234>
.

**Comment by EPTamminga** [comment]
Yes, I used both a registered/logged in user as well as no login (anonymous).

I get an js error on you site in Telerik on the 2nd click on the month:

TypeError: a[b] is not a function


If you move the module to a plain page with the default DNN out of the box skin, is the error there as well?

Met vriendelijke groet,
Ernst Peter Tamminga

Van: davegambino [mailto:notifications@github.com]
Verzonden: woensdag 4 november 2015 15:51
Aan: DNNCommunity/DNN.Events <DNN.Events@noreply.github.com>
CC: Ernst Peter Tamminga <ernst.peter.tamminga@xcess.nl>
Onderwerp: Re: [DNN.Events] Next / Previous Month Control Not Working (#16)

Were you able to test this WITHOUT being logged in as a DNN User?



The problem does not happen when logged in. …. Only public visitors to the
website.



Here is an example of one of many of my sites that is having the problem:
http://saintbridgetchurch.org/Resources/Calendar.aspx



Can you think of what may be conflicting with my builds?



Thanks so much for your time.



*Dave Gambino*

dave@smbcreativegroup.com<mailto:dave@smbcreativegroup.com>

1-800-980-0906 x 705



*SMB Creative Group*



*Our Services*

www.CatholicChurchWebsites.com<http://www.CatholicChurchWebsites.com> | www.SMBCreativeGroup.com<http://www.SMBCreativeGroup.com>
<http://www.smbcreativegroup.com/>



*From:* Ernst Peter Tamminga [mailto:notifications@github.com]
*Sent:* Wednesday, November 04, 2015 8:41 AM
*To:* DNNCommunity/DNN.Events <DNN.Events@noreply.github.com<mailto:DNN.Events@noreply.github.com>>
*Cc:* davegambino <dave@smbcreativegroup.com<mailto:dave@smbcreativegroup.com>>
*Subject:* Re: [DNN.Events] Next / Previous Month Control Not Working (#16)



I verified & tried to repeat the problem but I could NOT reproduce it.

Plain vanilla DNN 7.3.3 (blank website) out of the box, Events 6.2.1;
Events installed on the single page, NO PROBLEM in clicking on the months
forward and backward

Repeated the same procedure with DNN 7.4.4, again, no problem.

Repeated the cycle with both Events Install version as well as Source
version. Again, no problem.

Repeated for DNN733 with (HOST) Client Resource Management ON,
minify/combine CSS and JS. Again ,no problem.

Test environment:
Windows 8.1, SQL2014, IIS8.5

—
Reply to this email directly or view it on GitHub
<https://github.com/DNNCommunity/DNN.Events/issues/16#issuecomment-153747234>
.


—
Reply to this email directly or view it on GitHub<https://github.com/DNNCommunity/DNN.Events/issues/16#issuecomment-153750616>.




CEO
[XCESS expertise center b.v.]<https://www.xcess.nl/>    XCESS expertise center b.v.
Storkstraat 19
3833 LB Leusden, NL
I www.xcess.nl<https://www.xcess.nl>    M
D
T
E

+31-6-21564750
+31-33-4335101
+31-33-4335151
ernst.peter.tamminga@xcess.nl




________________________________

Dit e-mail bericht is alleen bestemd voor de geadresseerde, verstrekking aan en gebruik door anderen is niet toegestaan. Indien u niet de geadresseerde bent, wordt u vriendelijk verzocht de verzender hiervan op de hoogte te stellen en het bericht te verwijderen. In verband met de elektronische verzending kunnen aan de inhoud van dit bericht geen rechten worden ontleend. Tenzij schriftelijk anders is overeengekomen, zijn op al onze rechtsbetrekkingen de XCESS leveringsvoorwaarden<https://www.xcess.nl/Portals/0/Downloads/%5bXCESS%5d%20Algemene%20Leveringsvoorwaarden08052008NL.pdf> van toepassing. Deze zijn gedeponeerd bij de Kamer van Koophandel Amersfoort onder nummer 31047117 en bij de griffie van de arrondissementsrechtbank te Amsterdam onder nummer 36/2003 en worden op verzoek toegezonden. Toepasselijkheid van eventuele inkoop- of andere voorwaarden van opdrachtgever dan wel van derden wordt dan ook uitdrukkelijk van de hand gewezen door XCESS.

**Comment by EPTamminga** [comment]
@davegambino Were you succesful in placing the module on a clean page with a default DNN page skin?

**Comment by davegambino** [comment]
I will do that today.  What skin should I select?



*Dave Gambino*



*From:* Ernst Peter Tamminga [mailto:notifications@github.com]
*Sent:* Monday, November 09, 2015 1:41 AM
*To:* DNNCommunity/DNN.Events <DNN.Events@noreply.github.com>
*Cc:* davegambino <dave@smbcreativegroup.com>
*Subject:* Re: [DNN.Events] Next / Previous Month Control Not Working (#16)



@davegambino <https://github.com/davegambino> Were you succesful in placing
the module on a clean page with a default DNN page skin?

—
Reply to this email directly or view it on GitHub
<https://github.com/DNNCommunity/DNN.Events/issues/16#issuecomment-154985420>
.

**Comment by davegambino** [comment]
So here are the results.



You are correct that it must be skin related.



I have tested that it appears to be fine on these sites of mine:

·         http://group2.connectingmembers.com/bravo/Resources/Calendar.aspx

·         http://group2.connectingmembers.com/flex/Resources/Calendar.aspx

·         http://group2.connectingmembers.com/simple/Resources/Calendar.aspx



However, I am having problems on these 2 site skins:

·
http://group2.connectingmembers.com/cleanweb/Resources/Calendar.aspx

·         http://saintbridgetchurch.org/Resources/Calendar.aspx



Would you have any idea where I could begin trying to find what the problem
is?  In your email below, you reference a Telerik js error.



All of these sites are on the same DNN Host so what could possibly change
between them?



*Dave Gambino*

dave@smbcreativegroup.com

1-800-980-0906 x 705



*SMB Creative Group*



*Our Services*

www.CatholicChurchWebsites.com |  www.SMBCreativeGroup.com
<http://www.smbcreativegroup.com/>



*From:* Ernst Peter Tamminga [mailto:notifications@github.com]
*Sent:* Wednesday, November 04, 2015 8:58 AM
*To:* DNNCommunity/DNN.Events <DNN.Events@noreply.github.com>
*Cc:* davegambino <dave@smbcreativegroup.com>
*Subject:* Re: [DNN.Events] Next / Previous Month Control Not Working (#16)



Yes, I used both a registered/logged in user as well as no login
(anonymous).

I get an js error on you site in Telerik on the 2nd click on the month:

TypeError: a[b] is not a function


If you move the module to a plain page with the default DNN out of the box
skin, is the error there as well?

Met vriendelijke groet,
Ernst Peter Tamminga

Van: davegambino [mailto:notifications@github.com <notifications@github.com>]

Verzonden: woensdag 4 november 2015 15:51
Aan: DNNCommunity/DNN.Events <DNN.Events@noreply.github.com>
CC: Ernst Peter Tamminga <ernst.peter.tamminga@xcess.nl>
Onderwerp: Re: [DNN.Events] Next / Previous Month Control Not Working (#16)

Were you able to test this WITHOUT being logged in as a DNN User?



The problem does not happen when logged in. …. Only public visitors to the
website.



Here is an example of one of many of my sites that is having the problem:
http://saintbridgetchurch.org/Resources/Calendar.aspx



Can you think of what may be conflicting with my builds?



Thanks so much for your time.



*Dave Gambino*

dave@smbcreativegroup.com<mailto:dave@smbcreativegroup.com>

1-800-980-0906 x 705



*SMB Creative Group*



*Our Services*

www.CatholicChurchWebsites.com<http://www.CatholicChurchWebsites.com
<http://www.CatholicChurchWebsites.com%3chttp:/www.CatholicChurchWebsites.com>>
| www.SMBCreativeGroup.com<http://www.SMBCreativeGroup.com
<http://www.SMBCreativeGroup.com%3chttp:/www.SMBCreativeGroup.com>>
<http://www.smbcreativegroup.com/>



*From:* Ernst Peter Tamminga [mailto:notifications@github.com
<notifications@github.com>]
*Sent:* Wednesday, November 04, 2015 8:41 AM
*To:* DNNCommunity/DNN.Events <
DNN.Events@noreply.github.com<mailto:DNN.Events@noreply.github.com>>
*Cc:* davegambino <
dave@smbcreativegroup.com<mailto:dave@smbcreativegroup.com>>
*Subject:* Re: [DNN.Events] Next / Previous Month Control Not Working (#16)



I verified & tried to repeat the problem but I could NOT reproduce it.

Plain vanilla DNN 7.3.3 (blank website) out of the box, Events 6.2.1;
Events installed on the single page, NO PROBLEM in clicking on the months
forward and backward

Repeated the same procedure with DNN 7.4.4, again, no problem.

Repeated the cycle with both Events Install version as well as Source
version. Again, no problem.

Repeated for DNN733 with (HOST) Client Resource Management ON,
minify/combine CSS and JS. Again ,no problem.

Test environment:
Windows 8.1, SQL2014, IIS8.5

—
Reply to this email directly or view it on GitHub
<https://github.com/DNNCommunity/DNN.Events/issues/16#issuecomment-153747234>

.


—
Reply to this email directly or view it on GitHub<
https://github.com/DNNCommunity/DNN.Events/issues/16#issuecomment-153750616>.





CEO
[XCESS expertise center b.v.]<https://www.xcess.nl/> XCESS expertise center
b.v.
Storkstraat 19
3833 LB Leusden, NL
I www.xcess.nl<https://www.xcess.nl
<http://www.xcess.nl%3chttps:/www.xcess.nl>> M
D
T
E

+31-6-21564750
+31-33-4335101
+31-33-4335151
ernst.peter.tamminga@xcess.nl




________________________________

Dit e-mail bericht is alleen bestemd voor de geadresseerde, verstrekking
aan en gebruik door anderen is niet toegestaan. Indien u niet de
geadresseerde bent, wordt u vriendelijk verzocht de verzender hiervan op de
hoogte te stellen en het bericht te verwijderen. In verband met de
elektronische verzending kunnen aan de inhoud van dit bericht geen rechten
worden ontleend. Tenzij schriftelijk anders is overeengekomen, zijn op al
onze rechtsbetrekkingen de XCESS leveringsvoorwaarden<
https://www.xcess.nl/Portals/0/Downloads/%5bXCESS%5d%20Algemene%20Leveringsvoorwaarden08052008NL.pdf>
van toepassing. Deze zijn gedeponeerd bij de Kamer van Koophandel
Amersfoort onder nummer 31047117 en bij de griffie van de
arrondissementsrechtbank te Amsterdam onder nummer 36/2003 en worden op
verzoek toegezonden. Toepasselijkheid van eventuele inkoop- of andere
voorwaarden van opdrachtgever dan wel van derden wordt dan ook
uitdrukkelijk van de hand gewezen door XCESS.

—
Reply to this email directly or view it on GitHub
<https://github.com/DNNCommunity/DNN.Events/issues/16#issuecomment-153753595>
.
