### ISSUE TITLE
Upgrade to Events 7.0.1 not migrating settings or saving settings.

### ISSUE THREAD

**Issue by james7342** [DNNCommunity/DNN.Events#161]
## Describe the bug
Upgraded my production site DNN 9.1.1 to Events 7.0.2 and noticed what appears to be a bunch of settings defaulted. I can update the settings and all appears to be saved correctly. No errors nothing. Once you restart application all the prior set settings are gone. I restored the site back and tried it again with version step upgrade to Events 7.0.0 and received the known Invalid Cast Error. Proceed to upgrade to 7.0.1 and observed the issue again.

No errors observed during upgrades. Unable to provide logs at the moment as had to restore site. What's weird is I have Events 7.0.3 installed on my test/dev without issue. It was upgraded from 6.3.1 to 7.0.0, 7.0.1, 7.0.2, and 7.0.3 and is not experiencing the issue.

**Comment by james7342** [comment]
Not sure what this issue is. I've successfully upgrade to DNN 9.2.2 and the 6.3.1 module is working without issue or any issues I've been able to detect at the moment. Going to stay here for now. Willing to troubleshoot and pull logs if required. I have exported the Modules SQL values for settings from both environments if some wants to take a look at those.

**Comment by james7342** [comment]
I’ll added I didn’t try 7.0.3 release due to the installation error and prerelease classification because of it. If there has been changes in 7.0.3 that is believed to resolve this willing to try it.

**Comment by james7342** [comment]
Just did some more testing in my Dev/Test environment with 7.0.3. It's not saving settings either. Even though things look good. I tried to update the theme today. I set to use standard theme - default. Pressed save and notice nothing changed. Went back to check if setting was saved. Still using custom theme. Tried again with same results. So I thought my dev/test was good in actuality it's broke also. Any ideas. Appears to be a few issues with the conversion. I'm more than willing to have a webex with someone to talk a look at.

**Comment by EPTamminga** [comment]
There are some issues with some settings where the mix of lowercase and uppercase in the settings name internally in the C# code and the existing storage on SQL server. This mismatch started during the conversion to C# (Version 7.0) and the implementation of the new DNN settings API. The API makes a difference between lowercase and uppercase in names of settings, whereas the queries on SQL do not.
I am working on a database script to correct this in the upcoming release of Events.
