### ISSUE TITLE
Incorrect recurring image path in event detail

### ISSUE THREAD

**Issue by chadwixk** [DNNCommunity/DNN.Events#167]
## Describe the bug
DNN 9.2.2 / Events 7.0.2
When viewing a recurring event, the path to the recurring image is incorrect and missing the `\Events\` directory.

Here is what is rendering:
`<img src="https://mysite.com/DesktopModules//Images/rec.gif" class="EventIconRec" alt="Recurring Event">`

Here is what should be rendering:
`<img src="https://mysite.com/DesktopModules/**Events**/Images/rec.gif" class="EventIconRec" alt="Recurring Event">`

Is there anyway to fix this without source code? I looked through the desktop module Events folder so see if I could find anything for the [event:recurring] token, but I didn't see a resource file, etc...anything text based to edit.

**Comment by EPTamminga** [comment]
The token replacement has to be done in the source, so I do not expect that you find an editable replacement string somewhere in an install pack.

**Comment by chadwixk** [comment]
Ok, thanks. Then let this serve as an open bug for consideration.

**Comment by EPTamminga** [comment]
I am working on an update version 7.0.4. I will try to solve this as well

**Comment by EPTamminga** [comment]
Found and corrected. Should be solved V07.00.04

**Comment by EPTamminga** [comment]
I cannot reproduce this in my current version (07.00.03). The image path is correct:
http://dnn922.local/DesktopModules/Events/Images/rec.gif
