### ISSUE TITLE
Update Template Not Working - Error: cmdUpdateTemplate_Click is not defined

### ISSUE THREAD

**Issue by chadwixk** [DNNCommunity/DNN.Events#171]
## Describe the bug
DNN 9.2.2 Events 7.0.2

Templating feature is great, but it is not working, in that you can't update any changes you make to the template.

## To Reproduce
Make changes to template
Click Update Template link
Get error: `cmdUpdateTemplate_Click is not defined`

## Screenshots
![image](https://user-images.githubusercontent.com/5115308/53979134-3186cc80-40ca-11e9-8f91-7bbccf09f5fc.png)

**Comment by EPTamminga** [comment]
This is solved in V 07.00.03
