### ISSUE TITLE
DNN 8.0 Update References

### ISSUE THREAD

**Issue by thabaum** [DNNCommunity/DNN.Events#18]
Telerik controls have been moved to 3rd party in DNN 8.0 Beta,  Can you release a beta 8.0 version  Or include telerik in a new release?

**Comment by EPTamminga** [comment]
Telerik will be available in DNN8, but there are breaking changes in the DNNPlatform with regards to the DNN/Telerik based controls. Work is being done to get an Events that will install, upgrade and work in DNN8.

**Comment by EPTamminga** [comment]
Release Events 6.3.0 published.
