### ISSUE TITLE
Events are disappearing from the Calendar! Please help.

### ISSUE THREAD

**Issue by thosalbert** [DNNCommunity/DNN.Events#191]
Hi - I'm using Events 6.3.0 inside DNN 9.1.1

Today I noticed that events on the Calendar disappear and are not appearing consistently. 

I can make this behavior happen by looking at a month with events listed on some dates. Then, if I click to the next month, and back to the original month, the Events are all gone! The Month View is shown, but the events are all missing! If I do a hard refresh of the page, the Events come back and are shown.

Any Idea why this happens, How can I fix this?

Thanks

Tom

**Comment by EPTamminga** [comment]
I tried to reproduce the behaviour you mention, but it works correctly with me (DNN911, Events 630).
Can you specify some more? Size of the site, # of Events, # of subcalendars, special security settings, etc,
When did the behaviour change? WHat happend around that time? DO you ahve DBA management tasks in place, etc.
Is the site publically viewable?

**Comment by thosalbert** [comment]
Thanks for your response Ernst - 
Here is the site:
http://santacruzcountycounts.us/
The Events Calendar is down at the bottom of the page. 
The problem seems to be timing related. I don't think anything specifically changed to cause this behavior to start. 
I put in a javascript timeout (on the skin file) to cause a delay in the page execution, which fixes the problem when the page is loaded. So you should see the June events (four of them) when you load the page. 
However, you can see the problem if you click on Next Month (July). No events are visible when you click on that page (though there are actually three Events ) . I can get these events to show if I do a hard refresh on the page (with the July month showing), and hold down the key to cause about a second delay before the page loads. When I do that, I can see the (three) July Events. 
(I'm also seeing a problem with clicking to Week View or List view, but I think this is only on Mac browser) 
I set up a separate page using the same existing Calendar module, but a different skin:
http://santacruzcountycounts.us/testcalendar.aspx
I wanted to see if the skin was causing the problem, but the behavior seems the same. Again, after clicking on next month (July), if I do a hard refresh and delay for a second or so, the Events show up. (On this page, the List and Week Views work as well. )
thanks
Tom

**Comment by EPTamminga** [comment]
Can you answer some of the questions that I put in my earlier comment? About the configuration etc.?

**Comment by thosalbert** [comment]
Hi again Ernst - 
It's a simple Events Calendar - no sub-calendars, about ten events currently. I don't know if there was any change which caused it to break ( I just heard about it from a customer) . No recent upgrades, etc. No DBA management tasks.

To be more clear, the problem occurs when clicking on the next (or previous) month (Currently July or May). Events which have been created don't appear, but if you refresh the page a couple of times (or do a hard refresh) , the events show up. 

Good news! I was just able to fix the problem by, in General Settings, under Look and Feel Settings, changing "Enable Location Select" to "Multiple Selection" (it was set for "Single Selection" before). 

I confirmed that when I set "Enable Location Select" back to "Single Selection" it causes the problem to occur. 

Here's a test page which has two Event Calendars on it 
http://www.santacruzcountycounts.us/testcalendar.aspx

Both calendars have a test event on July 1. The one on top has Enable Location Select: set to Multiple Selection, the one on the bottom is set to "Single Selection". When you click July, you'll see the event on the top calendar, but not on the bottom calendar. However, once you are looking at July, if you do a hard refresh, you'll see the event on the bottom calendar.

-Tom

**Comment by EPTamminga** [comment]
When I try to access the site on its home page, (http://www.santacruzcountycounts.us/), I get a timeout, and the home page does not load at all (BTW I am located in NL). 

I think there is something wrong with the site and/or hosting server which is not directly related to the Events module.

My normal way of working for these type of problems is to make a download and recreate the site locally, so you can experiment and find out what is wrong.

**Comment by EPTamminga** [comment]
No response received. Closing issue. Reopen the issue if you still have not found the solution.
