### ISSUE TITLE
Social Group Journal Issue

### ISSUE THREAD

**Issue by teambound** [DNNCommunity/DNN.Events#20]
When used in social groups, the events module posts to the journal but with a journal security key of U(Userid here) which prevents anyone in the group from seeing the event in group journal list except for the user entering it. There needs to be a way for the user to set the visibility of the journal or at least default to group visibility. Is there a setting I missed? I see other modules create 2 journal security keys, one for the user UUserid and one for the group  E.

Thanks!

**Comment by teambound** [comment]
Has this been verified and corrected?

Thanks

**Comment by EPTamminga** [comment]
This has not been verified yet.
