### ISSUE TITLE
Datepicker is not working on any page

### ISSUE THREAD

**Issue by Git07Omkar** [DNNCommunity/DNN.Events#200]
Datepicker is not working on any page.
Not able to select any date in the date picker.

**Comment by thabaum** [comment]
https://github.com/react-native-community/react-native-datetimepicker#react-native-datetimepicker

Should we move to react?  I am starting to dive into this and just feels like maybe it needs brought to life somehow along with the DNN Forums.

I have to learn it to develop anything with the DNN PersonaBar so maybe I can apply the same things to the event module a little and then to the forums if I get good at it.

I just am not sure which datepicker to go with.

You may have something else going on.  Can you explain the environment, what version of DNN you are using and which version of Events module.   I just recently installed and setup calendars on the latest version of DNN and was able to setup events.  Although I think it can be improved it worked.

**Comment by Git07Omkar** [comment]
I have to use this module in DNN 9.3.1

**Comment by Git07Omkar** [comment]
Also, I have to use this module in the Norwegian language, which follows the "22.10.19" date pattern.
It seems like this issue is only for the Norwegian language, as its working fine for American English which follows the "22/10/19" date pattern.

**Comment by EPTamminga** [comment]
Datepicker is fixed in Events 07.00.05, available as (pre) release.
