### ISSUE TITLE
Enrollment box has empty characters

### ISSUE THREAD

**Issue by james7342** [DNNCommunity/DNN.Events#213]
## Describe the bug
Testing 7.0.5 and created an event that allowed enrollment. Unable to enter enrollment number or what appears to not be entering number. Upon further investigation it looks like box contains blank characters or spaces making it difficult to see number entered.

## To Reproduce
1. Create event that allows for enrollment 
2. Try to enroll on event details page and enter number in text box. 
3. Unable to see data entered in enrollment box IE: 1.
4. Selecting text in the box with mouse and notice selecting of blank characters
5. Delete blank characters and then try enter enrollment number again and can now see number entered.

## Expected behavior
No blank characters and user able to see enrollment number

## Screenshots
Can provide upon request if needed.

## Error Log
N/A

**Comment by james7342** [comment]
I edited the EventDetails.ascx file and made the enrollment text box to width 200 to show the issue in the attached image.
![screenshot_1122](https://user-images.githubusercontent.com/27960723/74592605-bca95b80-4fd7-11ea-9918-2827070037c4.png)

As you can see he default value of 1 is there, but has spaces round the value. So when the box is on 30 (Default) you cannot existing value of 1.

**Comment by james7342** [comment]
Looks to be a formatting issue with the EventDetails.ascx page. I was able to resolve by adjusting the below.

Existing: 
<div class="SubHead DetailEnrollRight">
            <div id="enroll3" runat="server" visible="false">
                <asp:Label ID="lblNoEnrolee" runat="server" resourcekey="lblNoEnrolee" class="DetailEnrollLabel" Width="100px">No. of Enrolees</asp:Label>&nbsp;
                **<asp:TextBox ID="txtNoEnrolees" runat="server" CssClass="NormalTextBox"
                             Font-Size="8pt" MaxLength="3" Width="30">
                    1
                </asp:TextBox>**&nbsp;
                <asp:Label ID="lblMaxNoEnrolees" runat="server">(Max 1)</asp:Label>&nbsp;
                <asp:RangeValidator ID="valNoEnrolees" runat="server"
                                    ControlToValidate="txtNoEnrolees" MinimumValue="1" MaximumValue="1" Display="Dynamic" Type="Integer" cssclass="dnnFormMessage dnnFormError"
                                    ValidationGroup="EventSignup">
                </asp:RangeValidator>
                <asp:RequiredFieldValidator ID="valNoEnrolees2" ValidationGroup="EventSignup" runat="server" cssclass="dnnFormMessage dnnFormError"
                                            ControlToValidate="txtNoEnrolees" Display="Dynamic">
                </asp:RequiredFieldValidator>
            </div>

Adjusted:
<div id="enroll3" runat="server" visible="false">
                <asp:Label ID="lblNoEnrolee" runat="server" resourcekey="lblNoEnrolee" class="DetailEnrollLabel" Width="100px">No. of Enrolees</asp:Label>&nbsp;
                **<asp:TextBox ID="txtNoEnrolees" runat="server" CssClass="NormalTextBox" Font-Size="8pt" MaxLength="3" Width="30">1</asp:TextBox>**&nbsp;
                <asp:Label ID="lblMaxNoEnrolees" runat="server">(Max 1)</asp:Label>&nbsp;
                <asp:RangeValidator ID="valNoEnrolees" runat="server"
                                    ControlToValidate="txtNoEnrolees" MinimumValue="1" MaximumValue="1" Display="Dynamic" Type="Integer" cssclass="dnnFormMessage dnnFormError"
                                    ValidationGroup="EventSignup">
                </asp:RangeValidator>
                <asp:RequiredFieldValidator ID="valNoEnrolees2" ValidationGroup="EventSignup" runat="server" cssclass="dnnFormMessage dnnFormError"
                                            ControlToValidate="txtNoEnrolees" Display="Dynamic">
                </asp:RequiredFieldValidator>
            </div>

**Comment by EPTamminga** [comment]
Sharp spot.  Probably a result of editing and/or formatting in an editor that added line breaks for long lines.

I will clean-up the .ascx and create a new release
