### ISSUE TITLE
Email For Reminder

### ISSUE THREAD

**Issue by irzum** [DNNCommunity/DNN.Events#217]
I am not getting Emails on time I guess it might be a time zone issue, I received the email after a day.
how can I resolve this and get the reminder email on time that I set

**Comment by EPTamminga** [comment]
Datering with TZ is a complex matter. Windows server, sql server, portal settings, user profile, language setting, Events module setting, event setting, DNN scheduler run, email handling on hid smtp server, email on the client, all can have an influence.
Start with inspecting the portal settings and enable TZ display in events module and the events. Have the scheduled task run every 5 minutes or so. Use a email capture app (I use papercut) on your local machine, so emails are handled locally during testing
