### ISSUE TITLE
Export event is throwing exception

### ISSUE THREAD

**Issue by VickiChinyl** [DNNCommunity/DNN.Events#218]
Object reference not set to an instance of an object.

GetAdjustment() is returning null where it's not being handler in CreatevTimezones().

To replicate:-
Event Time Zone = (UTC+08:00) Perth
Event Start Date = 5/25/2020 3:00 PM
Event End Date = 5/25/2020 4:00 PM

![Capture](https://user-images.githubusercontent.com/52092517/82870870-3d76dc80-9f63-11ea-84cf-442adec1bd19.PNG)

**Comment by EPTamminga** [comment]
I cannot reproduce it. Can you provide some more info?

* Module settings for time zone
![image](https://user-images.githubusercontent.com/5859855/82991605-394bcd00-9ffe-11ea-822d-e23457be3407.png)

Event data:
![image](https://user-images.githubusercontent.com/5859855/82999105-d4e23b00-a008-11ea-92cc-e861a26408a8.png)


* Version of Events
![image](https://user-images.githubusercontent.com/5859855/82999194-f7745400-a008-11ea-9c20-e2dec3944d0b.png)

**Comment by VickiChinyl** [comment]
Hi, 

Here the details

![0_2020-05-28 09_32_32-test perth _ Home](https://user-images.githubusercontent.com/52092517/83089622-5ac5bb00-a0c9-11ea-93c2-105c79764e58.png)

1. Perth time zone - Export error

- Setting to Perth time zone
![2_2020-05-28 09_41_24-Test Perth _ Home](https://user-images.githubusercontent.com/52092517/83089682-85177880-a0c9-11ea-9546-30dfa393d338.png)

- Created a new event and Export event
![3_2020-05-28 09_41_24-Test Perth _ Home](https://user-images.githubusercontent.com/52092517/83089714-96608500-a0c9-11ea-8970-93f64eccfaa2.png)

- Error exception
![4_2020-05-28 09_44_38-Object reference not set to an instance of an object](https://user-images.githubusercontent.com/52092517/83089754-ac6e4580-a0c9-11ea-8c16-305b9f575f67.png)

2. US & Canada time zone - Export successful

- Change to US and Canada time zone
![5_2020-05-28 09_44_38-Object reference not set to an instance of an object](https://user-images.githubusercontent.com/52092517/83089777-c3ad3300-a0c9-11ea-943a-f3e6f78adfed.png)

- Created a new event and Export event, an ics file successfully downloaded.
![6_2020-05-28 09_44_38-Object reference not set to an instance of an object](https://user-images.githubusercontent.com/52092517/83089791-cc056e00-a0c9-11ea-8cf0-48532fb3aabe.png)
