### ISSUE TITLE
Upgraded to DNN 8.0 and get the following error:

### ISSUE THREAD

**Issue by Nuzzi** [DNNCommunity/DNN.Events#22]
<div class="SelCategory SubHead">
Line 6:  		<asp:label id="lblCategory" runat="server" resourcekey="lblCategory"></asp:label>
Line 7:          <dnn:DnnComboBox ID="ddlCategories" runat="server" CheckBoxes="True" EnableCheckAllItemsCheckBox="true" 
Line 8:  		    AllowCustomText="False" DataValueField="Category" DataTextField="CategoryName"  InputCssClass="CategoryFormat" DropDownCssClass="CategoryFormat" CssClass="SelectCategory">
Line 9:  		</dnn:DnnComboBox>

Source File: /new/DesktopModules/Events/SubControls/SelectCategory.ascx    Line: 7

**Comment by Nuzzi** [comment]
Replaced the the 6.2.2 install code with the current github code, and get:

Parser Error

Description: An error occurred during the parsing of a resource required to service this request. Please review the following specific parse error details and modify your source file appropriately. 

Parser Error Message: Could not load type 'DotNetNuke.Web.UI.WebControls.DnnComboBox' from assembly 'DotNetNuke.Web, Version=8.0.0.809, Culture=neutral, PublicKeyToken=null'.

Source Error: 

Line 1:  <%@ Control Language="vb" AutoEventWireup="false" Codebehind="SelectCategory.ascx.vb" Inherits="DotNetNuke.Modules.Events.SelectCategory" %>
Line 2:  <%@ Register Assembly="DotNetNuke.Web" Namespace="DotNetNuke.Web.UI.WebControls" TagPrefix="dnn" %>
Line 3:  <%@ Register TagPrefix="dnn" Assembly="DotNetNuke.Web.Deprecated" Namespace="DotNetNuke.Web.UI.WebControls" %>

Source File: /new/DesktopModules/Events/SubControls/SelectCategory.ascx    Line: 1 

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1055.0

**Comment by jjmyrick** [comment]
I'm having the same issue. Any fix or workaround?

**Comment by Nuzzi** [comment]
Hello Gentlemen,

Are there any comments on this?  Will it be fixed?  I have two fairly important pages on my website using this module that I currently have to hide.

**Comment by EPTamminga** [comment]
It will be fixed, but I don't know when. Since it seems that I am currently the only one doing work here,  it certainly has to wait till I am back from holiday (end march). 
If someone could step in: a pull request with the fix is most welcome.

**Comment by Nuzzi** [comment]
Cool.  Thanks,  What does it take to contribute?  I have written modules before.  All c# though, have not dealt with VB much in my professional life.

**Comment by Nuzzi** [comment]
Well, interestingly, I downloaded the project from Github, recompiled it, put the DotNetNuke.Modules.Events.dll in the Bin directory of my site and now everything works.  So, I guess I am good.

**Comment by EPTamminga** [comment]
Good to advthat things work. I am puzzled why it did not work im the first place. 
Contribution can be done in any form of pull requests. 
IMO editing existing VB.net code is not so difficult if you know C# (same apllies the other way around).
