### ISSUE TITLE
Events are displayed one day too early

### ISSUE THREAD

**Issue by MaiklT** [DNNCommunity/DNN.Events#222]
## Describe the bug
When entering an event it is displayed one day before the actual event date.

## To Reproduce
1. Create a new event
2. Update
3. Look at the calendar
4. See the event on the wrong date

## Expected behavior
Event should be displayed on the correct date.

## Screenshots
Create event:

<img width="511" alt="Events-01" src="https://user-images.githubusercontent.com/7458140/84588479-0724d280-ae28-11ea-9c14-7c4a7b5999bd.png">

Calendar:

<img width="460" alt="Events-02" src="https://user-images.githubusercontent.com/7458140/84588500-418e6f80-ae28-11ea-862a-852e45a45776.png">

Also wrong date on details page:

<img width="467" alt="Events-03" src="https://user-images.githubusercontent.com/7458140/84588522-74d0fe80-ae28-11ea-8286-0387af56a0a9.png">

But when going to edit the event, the correct date is shown.

**Comment by MaiklT** [comment]
I should mention: when I export the event to an .ics file it shows the correct date there as well.

**Comment by PeterCasper** [comment]
Check for UTC vs local times.

Peter C

**Comment by EPTamminga** [comment]
Activate the setting to display the timezone, to inspect TZ of portal, module, event...

**Comment by MaiklT** [comment]
Portal TZ: UTC+1 Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
Event Module Standard Timezone: same
Primary Timezone: User
Secondary Timezone: Portal
Timezone per Event: No

When editing an event, I see the disabled dropdownlist that display the "normal" (UTC+1) timezone, but in the event details I see "(UTC-12:00) International Date Line West". There is no setting that points to that timezone.

The event module always worked fine, this happened after the last update to version 07.00.06.

**Comment by EPTamminga** [comment]
Wich Events version did you upgrade from? 
In the last 7.0.x versions there were only small fixes AFAIK, no serious data changes

**Comment by MaiklT** [comment]
Solved. The problem was that the timezone in the users' profiles have been set to UTC-12 (Date Line West). I don't know how this happened (as I had set all time zones correctly, when I created the users) - this must have been a problem with some DNN update...
