### ISSUE TITLE
Event Email Settings - Send Event New Emails - Cannot change from subscribe to never

### ISSUE THREAD

**Issue by dlloyd525** [DNNCommunity/DNN.Events#224]
## Describe the bug
I am attempting to change the Send Event New Emails option from Subscribers to Never.  When I select Never, click Save and reload the settings, the value remains Subscribers.

## To Reproduce
1. Go to Event Module Settings
2. Click on the Notification tab.
3. Change Send Event New Emails from Subscribers to Never.
4. Click Save.
5. Close Event Module Settings.
6. Open Event Module Settings, click on the Notification tab, The value remains Subscribers.

## Expected behavior
Change to Never.

## Error log
No errors are in the log file.

**Comment by james7342** [comment]
What version do you have deployed? Just tested this version 7.0.6 and it's appears to be working fine. The value is stored in the ModuleSettings table value "Neweventemails". The below SQL statement can be ran in the DNN SQL console and will provide your current values. Once you figure out the module ID Events is you should be able to change the value to Never. 
![screenshot_1742](https://user-images.githubusercontent.com/27960723/96160892-6de7f480-0ecb-11eb-90cd-9b4e11889146.png)

Select * from ModuleSettings where SettingName = 'Neweventemails'

If you're using an older version though I would recommend upgrading 7.0.6 first. Of course after a complete backup of you DDN site.

**Comment by EPTamminga** [comment]
No further reactions received.
