### ISSUE TITLE
Enrollment is Full Message

### ISSUE THREAD

**Issue by CubeDweller** [DNNCommunity/DNN.Events#226]
Concerning the Enrollment link at the top of an event detailed view.

If there is slots open it says "Enroll for this Event?"
If it is already past is says "Event has started, it is no longer possible to enroll."

But if the event is FULL there is NO message; Leaving (my angry) users looking for a way to enroll.

Am I missing something? Shouldn't it say something like "This event is Full."

Thank you, CD

**Comment by EPTamminga** [comment]
You can use tokens in the template for display (in the various display locations) to show the # of places, and the # of people already enrolled.

Have a look at the available tokens in the (Wiki) documentation of Events:
https://github.com/DNNCommunity/DNN.Events/wiki/Tokens-to-be-used-in-Templates  

Token|Description
-- | --
[event:maxenrollmentslabel] | Label of Max Enrolments
[event:maxenrollments] | Maximum number of enrolments for the event
[event:noenrollmentslabel] | Label of No. Enrolments
[event:noenrollments] | Number of people currently enroled for the event
[event:novacancieslabel] | Label of No. Vacancies
[event:novacancies] | Number of vacancies currently available for the event

**Comment by EPTamminga** [comment]
No more reactions
