### ISSUE TITLE
Casting Error

### ISSUE THREAD

**Issue by JaySMa** [DNNCommunity/DNN.Events#227]
Upgraded existing system from Evoq 8.5.0 to Evoq 9.6.3-2.  At the Evoq 9.2.2 upgrade, I updated the Events module to the latest version.

Updating one of our existing calendars and when trying to add a new event or update an existing, get the following pop-up error:
**_Error: is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Specified cast is not valid. ---> System.InvalidCastException: Specified cast is not valid. at DotNetNuke.Modules.Events.EditEvents.LoadCategory(Int32 category) at DotNetNuke.Modules.Events.EditEvents.LoadEvent() at DotNetNuke.Modules.Events.EditEvents.Page_Load(Object sender, EventArgs e) --- End of inner exception stack trace ---_**

Have found that when the "Enable Category Select" is set to none (which is how it's been configured), the error appears for add/edit of even/series.  Removing this allows us to add/edit events/series.

If we check "Restrict Categories", no events are displayed until we go back a month and forward to the current month.

Tried adding a brand new calendar and the above happens with the new calendar too.

Thank you.

**Comment by EPTamminga** [comment]
No support for Evoq, sorry.
