### ISSUE TITLE
Telerik Removal

### ISSUE THREAD

**Issue by JaySMa** [DNNCommunity/DNN.Events#228]
## Describe the bug
DNN v10 is going to fully remove Telerik from it's installations.  The [DNN Telerik Identifier Module](https://github.com/IowaComputerGurus/DnnTelerikIdentifier) is reporting the Events module is using the Telerik libraries.

## To Reproduce
1. Download and install the module above.
2. Run the module and it reports the Events module as using Telerik library.

## Additional context
DNN v9.8.0 makes Telerik removal a manual option currently.  v10 is going to be automatic and when this occurs, the Events module will be broken.

**Comment by valadas** [comment]
Related to #85 I am not sure if it's the only usage though.

**Comment by EPTamminga** [comment]
This subject is already covered by #85 and a known required enhancement for long.
Any donations of code is welcome
