### ISSUE TITLE
Friendly URLs

### ISSUE THREAD

**Issue by ajplopez** [DNNCommunity/DNN.Events#23]
This module could really use better URLs for the Event Details page.

The URLs currently look like this: www.mydomain.com/Calendar/ModuleID/1317/ItemID/2/mctl/EventDetails

It would be awesome if they looked something like this: 
www.mydomain.com/Calendar/mar-8-2016/top-shelf-happy-hour

Even if they had to have the module ID and item ID, it would be a better start than nothing.

**Comment by EPTamminga** [comment]
Good idea. 
Feel free to create a pull request with the required code changes.

**Comment by ajplopez** [comment]
Hah, I would if I knew how to do it. I put this in under this Issues
section to at least start the discussion.

Good idea.
Feel free to create a pull request with the required code changes.

—
Reply to this email directly or view it on GitHub
<https://github.com/DNNCommunity/DNN.Events/issues/23#issuecomment-194092825>
.
