### ISSUE TITLE
Delete clone event also delete parent from

### ISSUE THREAD

**Issue by carlos-andres** [DNNCommunity/DNN.Events#24]
Good Day i like to know if exist an way delete an event when is copied from another? At this time the module delete both on them.

**Comment by EPTamminga** [comment]
If you made a module copy, I think you created 2 display places for a single calendar, so updates will be on both places. This is normal DNN behaviour.

**Comment by carlos-andres** [comment]
Thank you very much for the prompt reply .. the downside is not to duplicate the module as such. The main problem is to create an event from another, I mean to clone .. if I delete children event is also delete the parent event

**Comment by EPTamminga** [comment]
You can edit a single event and not 'Update', but 'Save as copy'

**Comment by carlos-andres** [comment]
Right, when i got the "_copy" and try to delete it also delete the referer event too,

**Comment by carlos-andres** [comment]
you can see... the main event and clone using 'Save as copy'

![image](https://cloud.githubusercontent.com/assets/5489747/13758311/cfac1998-e9f6-11e5-8475-77cf1d0b93ea.png)

and when i delete child both are deleted check the db and i got

![image](https://cloud.githubusercontent.com/assets/5489747/13758451/871a8722-e9f7-11e5-84d0-7ce645d90045.png)

**Comment by EPTamminga** [comment]
It still puzzles me what yiu are trying to do. Have you tried to review the documentation of Events? Or looked as some video's with instructions of the Events module? Just Google on 'dotnetnuke events module' and look for video's.

I am on holiday atm and cannot do more for you, sorry.

**Comment by carlos-andres** [comment]
Thanks.. i do a research them.. and have a nice Holiday ..
