### ISSUE TITLE
Error after 9.10 Upgrade

### ISSUE THREAD

**Issue by CalaverasCountyWebmaster** [DNNCommunity/DNN.Events#242]
[NullReferenceException: Object reference not set to an instance of an object.]
   Components.EventModuleSettings.CreateEventModuleSettings(Int32 moduleId, String localResourceFile) +71
   Components.EventModuleSettings.GetEventModuleSettings(Int32 moduleID, String localResourceFile) +92
   Components.EventBase.get_Settings() +79
   Components.EventBase.GetThemeSettings() +27
   Components.EventBase.SetTheme(Panel ctlPnlTheme) +39
   DotNetNuke.Modules.Events.Events.Page_Load(Object sender, EventArgs e) +16
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +52
   System.Web.UI.Control.OnLoad(EventArgs e) +97
   DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e) +208
   System.Web.UI.Control.LoadRecursive() +61
   System.Web.UI.Control.LoadRecursive() +134
   System.Web.UI.Control.LoadRecursive() +134
   System.Web.UI.Control.LoadRecursive() +134
   System.Web.UI.Control.LoadRecursive() +134
   System.Web.UI.Control.LoadRecursive() +134
   System.Web.UI.Control.LoadRecursive() +134
   System.Web.UI.Control.LoadRecursive() +134
   System.Web.UI.Control.LoadRecursive() +134
   System.Web.UI.Control.LoadRecursive() +134
   System.Web.UI.Control.LoadRecursive() +134
   System.Web.UI.Control.LoadRecursive() +134
   System.Web.UI.<LoadRecursiveAsync>d__246.MoveNext() +539
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
   System.Web.Util.WithinCancellableCallbackTaskAwaiter.GetResult() +32
   System.Web.UI.<ProcessRequestMainAsync>d__523.MoveNext() +4853

[PageLoadException: Object reference not set to an instance of an object.]
   DotNetNuke.Services.Exceptions.Exceptions.ProcessPageLoadException(Exception exc, String URL) +469
   DotNetNuke.Framework.PageBase.OnError(EventArgs e) +744
   System.Web.UI.Page.HandleError(Exception e) +86
   System.Web.UI.<ProcessRequestMainAsync>d__523.MoveNext() +9165
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
   System.Web.Util.WithinCancellableCallbackTaskAwaiter.GetResult() +32
   System.Web.UI.<ProcessRequestAsync>d__515.MoveNext() +525
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
   System.Web.UI.<ProcessRequestAsync>d__554.MoveNext() +507
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
   System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar) +72
   System.Web.UI.Page.AsyncPageEndProcessRequest(IAsyncResult result) +76
   ASP.default_aspx.EndProcessRequest(IAsyncResult ar) +4
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9850009
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +50
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +163

**Comment by EPTamminga** [comment]
Please provide more information. 
- Is this with the standard theme? If not, try the standard theme
- What are the steps to reproduce?
- Is this also with a clean DNN 9.10.1 site?

**Comment by EPTamminga** [comment]
No reaction in months
