### ISSUE TITLE
Event Summary and Description

### ISSUE THREAD

**Issue by thabaum** [DNNCommunity/DNN.Events#29]
Not sure why but I can't really tell which editor is for the Summary and which is for the actual Description of the event.

It would be nice of this was a bit more clear with Summary or Full Description in bold at the top of each section for user input.

Also when I hover and click on the event all I see is the first editor's content.  

Maybe I need to play with the templates?

**Comment by EPTamminga** [comment]
Your templates for the events display rules it all.
