### ISSUE TITLE
Error in loading the solution with VS2013

### ISSUE THREAD

**Issue by davidchandra** [DNNCommunity/DNN.Events#3]
Hi,

I just cloned the repository and I ran into an error in opening the main project.  It seems that you may be using an MSBUILD extension for tasks that I may not have.  It will be great if you can share the extension you are using so I can also replicate.  This is the error I am getting, I am trying to see if I can solve this :-)

D:\github\DNN.Events\DotNetNuke.Events.vbproj : error  : The imported project "C:\Program Files (x86)\MSBuild\MSBuildCommunityTasks\MSBuild.Community.Tasks.Targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  D:\github\DNN.Events\Installation\Project.targets

Thanks!  BTW, this is a great module, I am trying to extend this with my special need which is to be able to select multiple events and be able to check out once instead of per event.

Regards,
David

**Comment by EPTamminga** [comment]
The MSBUild task routines are put in the open source as well. See the documentation here:
http://dnnevents.codeplex.com/documentation#Install

From version 5.1.0 MS Build is used to support the debug and release build processes. Look here for more details - http://dnntcmsbuild.codeplex.com/. DNN Events up to version 6.1.3 uses _DNNTc MSBuild1.9.0_.

If you want to remove the dependency from the automatic build with this MS Build structure, just remove all calls to the DNNtc attribute, remove the project.targets as file and remove the reference to the DNNtc in the solution file.
