### ISSUE TITLE
Whole Months worth of events not displaying

### ISSUE THREAD

**Issue by Sunspoticus** [DNNCommunity/DNN.Events#30]
DNN: 8.0.3
Events Module: 6.3.0

Noticed the event scheduler was throwing alot of errors, clicked a couple of events in the current month, no problem. switch to August 2016 or November 2016, no events displayed. Meanwhile I count 43 events in the DB (events table) for August and 40 or so for November. So something is preventing them from being displayed now and DNN just isn't upfront about the real problem... 

Could SEARCH be causing a problem?

Any ideas?

You can see the event calendar in question at http://extraordinarygamers.net/Events

**Comment by JaySMa** [comment]
I have the same issue, except it's for our October 2016 calendar.

The DB table shows 20 items, but when we look at the calendar; NOTHING.

Sad to see that you opened this issue on July 19th and there hasn't been a response.

**Comment by jasclar** [comment]
Same issue with month view, but with November 2016.
My List view also shows no items. However my Week view DOES show items.
I have "English (United Kingdom)" as default for the site, with "English (United States)" disabled.
Timezone for the calendar is "(UTC+00:00) Dublin, Edinburgh, Lisbon, London"

**Comment by jasclar** [comment]
I managed to work around this for my own purposes. In case it helps, this is what I did ...
I edited the [EventsGetByRange] stored procedure...

There seemed to be an issue with the date parameters being passed in, so I overrode the condition by adding a clause "or (1=1)" to force a "true" here. The module's own filtering can still restrict results enough for me.

/*   (E.EventTimeBegin >= @BeginDate AND E.EventTimeBegin < DATEADD(DAY,1, @EndDate))) */
   (E.EventTimeBegin >= @BeginDate AND E.EventTimeBegin < DATEADD(DAY,1, @EndDate)) or (1=1)) 

...and Category and Location might be null, so I made this change...

/*
   AND (e.Category in (SELECT * FROM dbo.[EventsSplitIDs](@CategoryIDs)) or @CategoryIDs = '-1')
   AND (e.Location in (SELECT * FROM dbo.[EventsSplitIDs](@LocationIDs)) or @LocationIDs = '-1')
*/
   AND (isnull(e.Category,'') in (SELECT * FROM dbo.[EventsSplitIDs](@CategoryIDs)) or @CategoryIDs = '-1')
   AND (isnull(e.Location,'') in (SELECT * FROM dbo.[EventsSplitIDs](@LocationIDs)) or @LocationIDs = '-1')
