### ISSUE TITLE
Issues returning events - Unsure of exact cause

### ISSUE THREAD

**Issue by relaxabyte** [DNNCommunity/DNN.Events#39]
I use DNN Events for a school at a university. Each department has its own calendar and every event is published to one of these calendars. Then, other Events modules are set up to display combinations of these calendars/categories (eg. a Upcoming Seminars calendar is configured with a "Seminars" category and a dept. calendar set up as a subcalendar). Right now, the database has 253 events from today forward. Of those, 228 events are within 365 days.  That's the size of our dataset, but it seems to cause issues and I want to know if anyone else is experiencing this, can add more detail, or provide a solution.

First odd occurrence (mid summer)
Our main calendar is set for all categories, pulls in each dept as a subcalendar, and looks 1000 days out. The RSS feed worked for a long time. Then it started to sporadically return empty. At first, I was able to get it to work by simply changing the number of days out to a new number (59-62 days out). Eventually, that stopped working too. I dropped the number of days out down to about 20 days and that seems stable again.

Second odd occurrence (today 10/25)
A mini calendar is set to show all categories, has a dept as a subcalendar, looks 365 days out, and displays only the first 5 upcoming events. We noticed that an event occurring tomorrow wasn't on the list. When trying to diagnose why it didn't appear, we couldn't see what made it different. When trying to copy or recreate the event, the mini calendar had all sorts of odd behavior (eg. After a copy, the original event showed, but not the copy. When the copy was deleted, the original disappeared). Remembering the RSS issue, I scaled back the mini calendar to 20 days out and everything appears to be back to normal.

Third odd occurrence (also today 10/25)
3) Our main calendar started to display zero events. I changed it from 1000 days to 900 days out and it started to work. (Note: there are no events being displayed between 900-1000 days out so it didn't decrease the number of events) That fix seems fine right now, but I fear that it will take a similar path as the RSS issue

Lesson/Hypothesis - There is some kind of threshold that the module seems to fail at for events over time. By adjusting the days, we have mitigated our issues, but it does not fix the issues. Does anyone have any insight or similar experience?

**Comment by relaxabyte** [comment]
Additional notes: on the third occurrence, I also had a month view on the same page. It did not recover by adjusting the days back/days ahead. It shows all previous and all future month events, but the current month is empty despite having events in the dataset.

**Comment by jasclar** [comment]
have you looked at issue #30 ? ... https://github.com/DNNCommunity/DNN.Events/issues/30 
I found a workaround that worked for me - it may resolve some of your issues?

**Comment by relaxabyte** [comment]
@jasclar  -In issue #30 , you suspected the incoming parameters to the stored procedure EventsGetByRange as the cause.  We created a table to capture the incoming parameters to the EventsGetByRange SP. When we test those parameters, the output is correct. It includes records from the missing month. The SP itself appears to be working as expected. Our guess is that the true issue is after the data output happens.

When we used your workaround, it did fill the missing month (why? no clue.). The Events List view was able to filter down the data, but the RSS feed changed from Today to X days to including every event in the DB. 

The RSS feed dropping data seems similar to the month dropping. Any function being used by both? Perhaps there is a bad argument somewhere, or a function firing before an async call is completed. Hopefully, this puts someone more familiar with the module's backend code on the right track. We'll keep looking into it.

**Comment by relaxabyte** [comment]
@jasclar  - We think we found the issue, which would include #30 . We hard coded the parameters into the stored procedure that the month view was sending to it. Then we played with different combinations of the dataset. The SP itself seemed to be working fine in terms of returning records properly every time, but it wasn't making its way to the month view. After much head scratching, we added an Order By to display it by datetime. Our missing month came back to life.

In our missing month, it had an event for every day. Someone set an event to span the entire month to act as a "Notice" about a registration being open. That may be too confusing to whatever function is attempting to sort the data to display on the month view. By sending it as a DateTime, it seemed to alleviate the issue.

See if adding this to the SP EventsGetByRange fixes it for you too. Remember to remove the #30 workaround if you still have it in place.

`order by
E.EventTimeBegin`

@EPTamminga - if that works, would you add it to the master?

**Comment by EPTamminga** [comment]
@relaxabyte With pleasure!

**Comment by jasclar** [comment]
I removed my workaround, added the "order by E.EventTimeBegin", and it returned the expected results. However, I then removed the "order by E.EventTimeBegin", and it STILL returned the expected results. ???
So presumably the current date/time has an impact, and possibly the timezone? Will look at this further when I can.

**Comment by relaxabyte** [comment]
So your november 2016 month works now either way? Id say that it might be because its now november, but our dropped month was october 2016 and it was October when it dropped. If we altered the date range of the month span at all, it worked. That's why your return all data approach probably worked.  That led us to the thought of it being an issue with calculating a multi-day event and getting clipped by the date parameters. Before we got into that theory, we added the order by and the month displayed again. on our test server, September dropped. the order by fixed both locations. revolving it again rrewrote it.
-------- Original message --------From: jasclar <notifications@github.com> Date: 11/2/16  12:59 PM  (GMT-05:00) To: "DNNCommunity/DNN.Events" <DNN.Events@noreply.github.com> Cc: relaxabyte <sublimnal7@aol.com>, Mention <mention@noreply.github.com> Subject: Re: [DNNCommunity/DNN.Events] Issues returning events - Unsure of exact cause (#39) 
I removed my workaround, added the "order by E.EventTimeBegin", and it returned the expected results. However, I then removed the "order by E.EventTimeBegin", and it STILL returned the expected results. ???

So presumably the current date/time has an impact, and possibly the timezone? Will look at this further when I can.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DNNCommunity/DNN.Events","title":"DNNCommunity/DNN.Events","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DNNCommunity/DNN.Events"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jasclar in #39: I removed my workaround, added the \"order by E.EventTimeBegin\", and it returned the expected results. However, I then removed the \"order by E.EventTimeBegin\", and it STILL returned the expected results. ???\r\nSo presumably the current date/time has an impact, and possibly the timezone? Will look at this further when I can."}],"action":{"name":"View Issue","url":"https://github.com/DNNCommunity/DNN.Events/issues/39#issuecomment-257928403"}}}

**Comment by jasclar** [comment]
OK - without the "order by E.EventTimeBegin", setting the server's date/time back caused the month's entries to disappear. Adding "order by E.EventTimeBegin", returned the expected results.

There was an event covering the whole of the month **preceding** the emptied month, which would have appeared in the few days in the table before the 1st of the month. For that event, EventDateBegin was NULL, EventDateEnd was NULL, EventTimeBegin contained the timestamp for the 1st of the preceding month, Duration was 44639.

**Comment by djamell** [comment]
I would love to try/test this, but I'm unsure about where exactly I'm supposed add this line in the SP.

Before the last END at line 118?

**Comment by james7342** [comment]
djamell, 

Correct add it just above the last line. Seems to have resolved my issue.

/****Fix for Month View issue Github issue #39***/
ORDER BY E.EventTimeBegin
END

**Comment by djamell** [comment]
Thanks james7342.  It works for me too.

@EPTamminga  - Will this make it into the next version?

**Comment by Starholme** [comment]
@james7342  Looks like this is caused by a broken sort within the code itself. Adding the ORDER BY clause masks the issue by ensuring it sorts in the correct order. See #49

**Comment by TheDeadlyBulb** [comment]
I can report that the "ORDER BY E.EventTimeBegin" fix solved a similar issue for us dealing with the Event List view.  Thanks to everyone who figured this out.

**Comment by EPTamminga** [comment]
Handled in DNN Events 07.00.00.
