### ISSUE TITLE
Token [IFNOTHASIMAGE] or equivalent 

### ISSUE THREAD

**Issue by jftsaraiva** [DNNCommunity/DNN.Events#42]
If I wanna show a default image when I don't have event image, whats the best approach? 

We only have:
```
[IFHASIMAGE]<a href="[event:imageurl]">[event:eventimage]</a>[/IFHASIMAGE]
```

it will be great if we had: [IFNOTHASIMAGE]

Any workaround?

**Comment by EPTamminga** [comment]
@jftsaraiva I do not see a direct work around, other than changing the code. Good suggestion BTW.
