### ISSUE TITLE
New subcalendar events not showing in calendar listing

### ISSUE THREAD

**Issue by BEhlbeck** [DNNCommunity/DNN.Events#47]
My main calendar is shown as a subcalendar on  another events module incidence on a single page. The secondary is displayed as a list.  When created it showed all events from the main calendar (as sub-calendar events) but when new events are added to the main calendar they are not showing up on the sub calendar.

Any idea what would be causing this?

**Comment by EPTamminga** [comment]
If I understand you @BEhlbeck correctly, you have switched the principle of master and subcalendar structure. 
A main calendar is the master, a subcalendar is a feed for the main calendar. The main summarizes the events of one or more sub-calendars. You should enter new events in the sub calendar, not in the main calendar.

**Comment by BEhlbeck** [comment]
Thanks for replying.  We are entering the events into the sub-calendar and after about 2 days they finally show up on the listing (which is the main calendar that also shows events from the subcalendar).  Is there a sceduled event that I need to change or add to scheduler?  http://www.sechelt.ca/City-Hall/Calendar  March 15th special finance meeting shows up on main calendar but not on listing.

**Comment by EPTamminga** [comment]
The event data from subcalendars is retrieved from the database when the main calendar is displayed, there is no background update schedule involved. Time zones discrepancies? Event list limitations (before/after current date)

**Comment by BEhlbeck** [comment]
Time zones the same and events before and after the missing event are shown.  i think it might be related to module caching. It is inheriting Memory Output Cache Provider, duration (seconds) 0 and I can't change it to None. It appears to allow the change to none but then goes back to memory.

**Comment by BEhlbeck** [comment]
We are running DNN 8.4.2 and I was unable to change the module cache to None from Memory.  I manually changed the module cache to None in the database and the issue persists. When adding an event to the sub-calendar it does not show on the listing.  Does anyone have this functionality working on DNN 8?

**Comment by Timo-Breumelhof** [comment]
EVOQ 8.4.2 that is :-)

**Comment by Timo-Breumelhof** [comment]
I just tested this in DNN platform (07.03.04) and it seems to be a Evoq only issue

**Comment by Timo-Breumelhof** [comment]
@EPTamminga Will this the reference fix (#49) be in a new release or is it in the 6.3.1 version already?

**Comment by EPTamminga** [comment]
@Timo-Breumelhof It is not in 6.3.1, I will add it to the release 6.3.2 I am working on.

**Comment by Timo-Breumelhof** [comment]
Ok, I though so. Thanks Ernst Peter.
