### ISSUE TITLE
Too many events causes the current month view to not work.

### ISSUE THREAD

**Issue by noahbast** [DNNCommunity/DNN.Events#48]
This is related to issue #19, but that does not describe the problem well.

We have a client who's calendar stopped working.  I did some testing, and ran SQL Profiler to track down the cause.

When viewing the calendar, it runs the following query:
exec dbo.EventsGetByRange @ModuleIDs=N'1565',@BeginDate='2016-09-07 16:45:13.987',@EndDate='2018-03-07 16:45:13.987',@CategoryIDs=N'-1',@LocationIDs=N'-1',@SocialGroupId=-1,@SocialUserId=-1

141 rows are returned.  No queries to fetch event details are run.

If you then click to  view the next month, it runs this query:
exec dbo.EventsGetByRange @ModuleIDs=N'1565',@BeginDate='2017-04-21 00:00:00',@EndDate='2017-06-11 00:00:00',@CategoryIDs=N'-1',@LocationIDs=N'-1',@SocialGroupId=-1,@SocialUserId=-1

11 rows are returned.

Note the much smaller date range.  Why is the default date range on a query to return events for only the current month so broad?  Just changing the date range will probably fix the problem.

This narrower query is followed by a series of queries to get more information about the events:
exec dbo.EventsLocationGet @Location=8,@PortalID=0

Note that none of these queries to get details are made when a large number of events are returned.

I edited some recurring events that were set to repeat until 2020 to only repeat until 2018 and the problem went away.

I don't know the breakpoint for when the current month stops working, but I suspect that it may be 100.

**Comment by james7342** [comment]
Running into the same issue. Looks like with the number events added tot eh calendar effects the month view. It was displaying find, but as I've added more events all of a sudden the month view is blank. You can still see the event if change to list view or reduce the number of events by using a category the month view will work again. If trying to view all events, blank 31 day month view. Making it really hard to use the module now. Can we get a fix for it?

**Comment by james7342** [comment]
Take a look at the fix for #39 . 
I added the ORDER BY statement to the SP EventsGetByRange and it seems to have resolved the issue for me. At least in initial testing.

/*Fix for Month View issue Github issue #39/
ORDER BY E.EventTimeBegin
END
