### ISSUE TITLE
Error Trying to Install on 7.4.0

### ISSUE THREAD

**Issue by colbydnn** [DNNCommunity/DNN.Events#5]
Tried to install using the Github download and it kept failing.  Downloaded the version from Codeplex and no issues.

Is there a different version I'm supposed to download?  The zip file from the Release page was the one that didn't work.

**Comment by EPTamminga** [comment]
I checked it. The release zip as mentioned here on GitHub is (only) a zip of the current sources in the VS project. As such, not an install zip to be used for DNN extension install. 
CodePlex is the current place for distribution. This might change in the future, once I got the grip on creating a full release page with all release elements here on GitHub.
