### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by pct3-com** [DNNCommunity/DNN.Events#52]
Moved website to a web farm system and getting this error while adding events. 
![service_unavailable](https://user-images.githubusercontent.com/29411408/27099034-32fc22b8-503f-11e7-8874-bdec9b1fb4bb.jpg)

**Comment by EPTamminga** [comment]
I have not seen this error before, bu I am also unable to test it in a webfarm. If you inspect to the DNN event log, you might find more useful information

**Comment by EPTamminga** [comment]
No response received
