### ISSUE TITLE
Purge Old Events not deleting Records from Event Table

### ISSUE THREAD

**Issue by djamell** [DNNCommunity/DNN.Events#53]
Running DNN 8.0.4 and Events 6.3.0

I'm seeing records that are a year old in the Events Table even though I have "Delete Events Older Than:" set 30 Days.

The Scheduled Task "DNN Events" is running successfully every hour.

The Events are all Recurring, setup as Weekly Events with a Repetition Frequency of 1 Week on a particular Day of the week.

Are the old records supposed to be deleted by the Scheduled Task?

Can I Delete the old records manually from the Events Table without causing problems?

**Comment by EPTamminga** [comment]
Cleanup events only takes place for individual events, not for events that are part of a master recurring event. The events of a recurring event remain for as long as the master recurring event is taking place.

Suggestion: create multiple adjacent recurring events with a limited timescale i.s.o. one recurring event that spans your whole period.

**Comment by djamell** [comment]
Ahhhh, I understand now.  I might suggest that you add the first two sentences of your reply to the Purge Old Events page in the Wiki.

As always, thanks for maintaining and supporting this important DNN Module.

**Comment by EPTamminga** [comment]
@djamell Wik editi: done.
