### ISSUE TITLE
Content inside square brackets not shown. is there an escape method?

### ISSUE THREAD

**Issue by vallatadellostilaro** [DNNCommunity/DNN.Events#55]
When in DESCRIPTION or in SUMMARY there are square brackets, the token replacement mechanism try to replace the content and shows nothing.

Is there an escape method for this?

Emanuele

**Comment by EPTamminga** [comment]
@vallatadellostilaro The Token replacement follows the standard rules/mechanism of DNN.

Here is a forum thread that describes how to use escape characters:

http://www.dnnsoftware.com/forums/threadid/462477/scope/posts/escape-text-html-token-replacement-square-bracket

Or here:
http://my-tokens.dnnsharp.com/how-to/escape-special-characters

**Comment by vallatadellostilaro** [comment]
Any chance to render things like 
<script type="application/ld+json">
        {
       "@context": "http://schema.org",
       "@type": "http://schema.org/ImageGallery",
       "associatedMedia":  [{...}]                 <------------------- here square brackets with content
}
</script>

**Comment by EPTamminga** [comment]
I am not sure if script can be saved in the summary field. 
For security reasons, the text input is cleaned from script. See line 1215 of EditEvents.assx.vb.
.Summary = objSecurity.InputFilter(ftbSummary.Text, PortalSecurity.FilterFlag.NoScripting)

**Comment by vallatadellostilaro** [comment]
Nope!

The script is stored and rendered as is. except for the javascript array [...] that is substituted with empty (by token replacement I think)
