### ISSUE TITLE
Can't get access to Phone No. Field in Event Enrollment

### ISSUE THREAD

**Issue by thosalbert** [DNNCommunity/DNN.Events#57]
I can't seem to find a token to access the Phone Number field that is built into the Enroll section of an Event.

On this page:
https://github.com/DNNCommunity/DNN.Events/wiki/Tokens-to-be-used-in-Templates

I found the token for the name: [event:signupusername] and Email address [event:signupuseremail] But I have no idea how to access the data in the Phone No. field.

-Tom

**Comment by EPTamminga** [comment]
Currently, the Phone number is not avaialble as token. I will add this as an enhancement request

**Comment by thosalbert** [comment]
Wonderful. Thanks for responding and letting me know.
Tom
