### ISSUE TITLE
URL Image not stored when add/update event

### ISSUE THREAD

**Issue by vallatadellostilaro** [DNNCommunity/DNN.Events#60]
Hi,

when an event is added or updated, the image address (external URL), is not stored in database.

after some investigations I discovered that in  EditEvents.ascx.vb file the statements at line 156

```
156                    Dim url As String = ctlURL.Url
157                    Dim urlType As String = ctlURL.UrlType
158                    ctlURL.Url = url
159                    ctlURL.UrlType = urlType

```

set the **ctlURL.Url** variable to an empty value. 

I tried to comment on line 158 and recompile, and now it seems to be working.

I hope I was helpful.

many greetings.

Emanuele Valenti

**Comment by TheDeadlyBulb** [comment]
I had the same issue with external URL and that commenting out line 158 and recompiling solved the issue.  Thanks Emanuele!  You saved me some serious time!
