### ISSUE TITLE
month view is not showing entries

### ISSUE THREAD

**Issue by srobbins** [DNNCommunity/DNN.Events#63]
We're using Events v6.3.1.  In list view we can see all entries for the current month (April 2018). If we switch to month view, however, we see no entries at all for April. Month view does show entries for the previous month and the next month, just not for April (even though they are listed in the list view).  What's going on? How can we fix this?

**Comment by EPTamminga** [comment]
Can you give a URL where I cans ee it?

**Comment by srobbins** [comment]
The URL is www.harvardpress.com

 

Under the Happenings tab, choose Community events, then look at Harvard Events.  It’s set to display the list view, which is fine. Week view is also fine, but month view is blank.  Also, if you look at March in month view, you can see the entries for the first days of April.  Similarly, the May month view shows entries for the last few days of April.

 

Thanks for taking a look at this.

**Comment by EPTamminga** [comment]
I see the problem. But I also see, when switching from list to month view, a short display of data next right to the month, that disappears. It also shows when I refresh the page.
Can there be some conflict of different views and/or sub-calendars with some filtering?

**Comment by srobbins** [comment]
I noticed that too but don’t know what’s causing it.  We have no sub-calendars, and are not using any filtering of categories.

 

And now, mysteriously, the April entries are showing in month view, but May’s entries do not!  Since yesterday I’ve added a few entries, but nothing out of the ordinary.

**Comment by srobbins** [comment]
I don’t think so. I’ve cleared the cache and restarted the application several times.

**Comment by PeterCasper** [comment]
Ernst,

I have the same fault. https://www.SBMH.com.au Some months are fine. Others are only viewable weekly. I also have instances in sub-calendars where the list view is empty but the weekly or monthly list is populated.

User: someone@example.com<mailto:someone@example.com>
Pass: TestPass

Please advise when finished viewing so that I may re-secure this user.

Peter

**Comment by EPTamminga** [comment]
@PeterCasper I have normal work to do today till late this evening. No time left some debugging.
Suggestion: re-secure the account asasp and mail me credentials (ernst.peter.tamminga at xcess.nl i.s.o. posting it here.

**Comment by srobbins** [comment]
It gets stranger.  I added three events this morning (May 4, 5, and 6), and now the month view displays correctly.  I’m thinking the problem is somehow in the data . . . maybe one or more entries being corrupt or non-standard in some way. 

I’m going to take a closer look at all the April and May events. Will let you know if I find anything amiss or if the problem recurs.

**Comment by EPTamminga** [comment]
@srobbins That could be the case. 
Is there special HTML or JavaScript somewhere in an event description or summary, that corrupts the browser rendering?

**Comment by gncube** [comment]
I am having the same error and problems on two different DNN installations were April is not showing any events and May is showing repeated events.

**Comment by EPTamminga** [comment]
@gncube: do you have a Public URL?

**Comment by gncube** [comment]
Found the error in my installation.

There was an event which started in April and had an end date in December 2018. When I deleted the event all is well now. So my contribution to the community is check the table dbo.Events and look for events ORDER BY [Duration] DESC

**Comment by EPTamminga** [comment]
@gncube Great, you found the problem and solved it
@srobbins Can this be the problem & solution for you as well?

**Comment by srobbins** [comment]
As mentioned earlier, our problem has disappeared for the moment, All three views (month, week, list) now display properly.  It does seem like there's some anomaly with the data though, so I'll be checking it carefully.
