### ISSUE TITLE
Events 7.0 Tooltips Not Working

### ISSUE THREAD

**Issue by james7342** [DNNCommunity/DNN.Events#70]
In Event 7.0 hovering over the tools icons in the upper right doesn't display tool tips any more. Verified on production site that 6.3.1 it does.
<img width="218" alt="screenshot_610" src="https://user-images.githubusercontent.com/27960723/40185778-4993c710-59a8-11e8-8865-4e7ddd2ae3f8.png">

**Comment by Mark-89** [comment]
Pull request has been made. The reference to the resource file had become broken during the upgrade process. 

Next release this will get implemented.
