### ISSUE TITLE
Module Load Exception Error on Ver 7.0 in DNN 9.2

### ISSUE THREAD

**Issue by worldheadquarters** [DNNCommunity/DNN.Events#72]
Added the module to a a page, made a few changes via the admin interface (display List Only was the main one).  Added no records (events or categories) to the system.  Generated the error below and now have no access to the ADMIN settings
=============================================
Error: Events is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: d:\webhost\dnndev.me\Website\DesktopModules\Events\EventRpt.ascx(12): error CS1061: 'ASP.desktopmodules_events_eventrpt_ascx' does not contain a definition for 'SelectCategory_CategorySelected' and no extension method 'SelectCategory_CategorySelected' accepting a first argument of type 'ASP.desktopmodules_events_eventrpt_ascx' could be found (are you missing a using directive or an assembly reference?) ---> System.Web.HttpCompileException: d:\webhost\dnndev.me\Website\DesktopModules\Events\EventRpt.ascx(12): error CS1061: 'ASP.desktopmodules_events_eventrpt_ascx' does not contain a definition for 'SelectCategory_CategorySelected' and no extension method 'SelectCategory_CategorySelected' accepting a first argument of type 'ASP.desktopmodules_events_eventrpt_ascx' could be found (are you missing a using directive or an assembly reference?) at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath) at DotNetNuke.Modules.Events.Events.LoadModuleControl() --- End of inner exception stack trace ---

**Comment by worldheadquarters** [comment]
Deleted the module and re-installed.  Seems to be working so far, but there seem to be s few bugs, which I will post as separate issues.

**Comment by EPTamminga** [comment]
Should be solved in DNN.Events 07.00.01

**Comment by arnekaulfuss** [comment]
> Should be solved in DNN.Events 07.00.01

- updated from 6.3.1 to 7.0.1 / 7.0.2 and throws the same error
- reproducible on several installs
- the error exist only on list in repeater-mode

trying to find the source of it

**Comment by arnekaulfuss** [comment]
fixed in 7.0.3

**Comment by curioustoknow2019** [comment]
7.0.3 is not fully released yet, 

> fixed in 7.0.3
