### ISSUE TITLE
Release 06.02.01 fails upgrade

### ISSUE THREAD

**Issue by MervHarvey** [DNNCommunity/DNN.Events#8]
Have just run the new release on a test site. The instal fails  - InnerException:Could not find file 'C:\DotNetNuke Sites\rvsupertramp-733-12.test\httpdocs\Install\Temp\03mhexh1\License.txt'.

Followed the path and License.txt in not in the Temp folder. It is however in the 'Installation' directory. Tried moving it to the Root but of course it fails again as the Temp folder is new on each attempt.

**Comment by EPTamminga** [comment]
This seems nothing to have to do with Events, but with general installation. Have you tried to install other modules? Better put this in the general forums on dnnsoftware.com?
