### ISSUE TITLE
Syntax code revealed in journal

### ISSUE THREAD

**Issue by thabaum** [DNNCommunity/DNN.Events#93]
## Describe the bug
When a user posts an event and it is displayed on the dnn journal module the syntax formatting code is shown and nothing is formatted.

## Expected behavior
Journal posting event summary with visual formatting instead of the html syntax code.

## Additional context
In my opinion when posting an event the "notes" form field should be labeled "Description" as this is what gets displayed everywhere in templates and on journal.  If a second form field for entering a summary in that would be ideal.

Replace and setup templates to accept as follows:
"Summary" (Instead of "Notes") as [EVENT:SUMMARY] for templates and is used for Journal posts.
 "Description"  (Instead of "Summary") as [EVENT:DESCRIPTION] for templates and is used for event details page links.

It is a bit confusing what is going to be displayed when you have two boxes to input information.   Does the "Notes" or the "Summary" suppose to get posted into the journal?   An option to set what gets posted in journal as a template feature   It should be a summary or introduction at top with a full description in the bottom.  Or just one place to put it all since when you click on a link by default you are redirected to an event with just the notes being displayed.

I see "Event Description" being what would match what is being used in templates.  And change "Notes" to "Summary" and put a tool tip mouse over to describe what is expected in each area.

Also when you hover over an event link on the calendar it shows the "notes" area which in my opinion is very unclearly labeled.  

The forms may need a little updating to move with the current changes.
I hope I am doing ok making this clear any questions please ask I will be happy to assist as I can.
Thank you.

**Comment by EPTamminga** [comment]
@thabaum Great description. Thank you. I will review it and see what we can do.
