### ISSUE TITLE
Import/Export

### ISSUE THREAD

**Issue by jncraig** [DNNCommunity/DNN.Events#96]
## Is your feature request related to a problem?
On multiple occasions, I've needed/wanted to mode a copy of an Events module to a new portal or to a new installation of DNN.  

## Describe the solution you'd like
I would like for the Events module to support Import/Export of all data (iPortable) so that the module and its contents can be moved to a new portal/site/installation.

**Comment by EPTamminga** [comment]
I am familiar with the need/wish for standard import/export, but it is a complex task. 
The Events data structure is not a simple straightforward one. It involves data & settings on host, portal, users and user groups level and individual data in module instance level, combined with data for eg. PayPal payments. 
I would prefer to split the import/export into a **definition only implementation** and a **definition + data implementation**. More work, but a better solution.
Both options require a serious amount of think & development work.

**Comment by PeterCasper** [comment]
Ernst,
I am trying to migrate 4 sites on an old Server 2012R2 host running 9.01.01 to a new Azure host running 9.02.02. Both servers have Events 7.0.3 installed. I am most disappointed in DNN with the site export / import feature, not just the Events module but with multiple modules & features. Even basic site configuration info such as site time zone, language, copyright, site logo & Favicon were not successfully transferred. Users, roles & basic page information was transferred but the damage is so great that I must give serious consideration to adopting another product.

Is evoq built on the same basic systems?

Peter

**Comment by valadas** [comment]
@PeterCasper, I also suggest you log the Dnn Import/Export issues at: https://github.com/DnnSoftware/Dnn.Platform but just the ones that are not module specific like the site logo & Favicon you mention.

**Comment by hcpctthree** [comment]
> I am familiar with the need/wish for standard import/export, but it is a complex task.
> The Events data structure is not a simple straightforward one. It involves data & settings on host, portal, users and user groups level and individual data in module instance level, combined with data for eg. PayPal payments.
> I would prefer to split the import/export into a **definition only implementation** and a **definition + data implementation**. More work, but a better solution.
> Both options require a serious amount of think & development work.

Is it possible to use a database query to copy all the events from one portal to another portal?

In essence is there a manual process?

**Comment by EPTamminga** [comment]
If you have enough experience in SQL, I assume that this is possible. The table structure is available as document. 
Please remember that there are portal and module settings as well that should be copied.

**Comment by hcpctthree** [comment]
Do you have a working example of the query that I can take a look at?

**Comment by EPTamminga** [comment]
Sorry, I do not have one query. 
The copy of Events content from one site to another will certainly take several queries, both for export as well as import. 
If the solution would consist of a single query, I would probably have added that to the module long time ago.

**Comment by wbhyde** [comment]
> If you have enough experience in SQL, I assume that this is possible. The table structure is available as document. Please remember that there are portal and module settings as well that should be copied.

Where is the table structure document?
